<script type="text/javascript">
    jQuery(document).ready(function() {
        $('select').select2();
        $('#save_user').click(
                function() {
                    if ($('#frmUser').valid()) {
                        $.post('<?php echo $this->baseUrl() ?>/admin/user/save/tabla/user/idname/id/idval/' + $("#id").val(), $("#frmUser").serialize(), function(data) {
                            if (data == 0) {
                                alert("Error: Please try again");
                            } else {
                                alert("Information successfully saved");
                                $( "#frmUser" ).submit();
                            }
                        }); //fin function data
                    }
                }); //end save user.

        $('.btnjson').click(
                function() {
                    var idval = $(this).attr('id')
                    var data = jQuery.parseJSON($('#id' + idval).val());
                    $('#frmUser').populate(data);
                    $('#password').val('');
                    $('#password').removeClass('required');
                }); //end btnjson function

        $('.clean').click(
                function() {
                    var form_id = $(this).closest("form").attr('id');
                    $('#' + form_id).trigger("reset");
                    $('#id').val('');
                }); //end clean form

    }); //End ready function      
</script>
<h2>User Administration</h2>
<form class="form-horizontal" name="frmUser" id="frmUser" action="<?php echo $this->baseUrl() ?>/user/user/" method="POST">
    <input type="hidden" id="profile_id" name="fields[user][profile_id]" value="1"> 
    <input type="hidden"
           id="updated" name="fields[user][updated]"
           value="<?php echo date('Y-m-d H:m:s'); ?>"> <input type="hidden"
           id="id" name="fields[user][id]" value=""> 
    <input type="hidden" id="id_client" name="fields[user][id_client]" class="id_client" value="<?php echo $this->idClient; ?>">

    <div class="form-group">
        <label class="col-sm-2 control-label">Full Name</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="fullname"
                   name="fields[user][fullname]" placeholder="Full Name">
        </div>
        <label class="col-sm-1 control-label">Phone</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="phone"
                   name="fields[user][phone]" placeholder="Phone">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">e-Mail</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required email" id="user"
                   name="fields[user][user]" placeholder="e-Mail">
        </div>
        <label class="col-sm-1 control-label">Password</label>
        <div class="col-sm-2">
            <input type="password" class="form-control required"
                   id="password" name="fields[user][password]"
                   placeholder="Password">

        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Position</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="position"
                   name="fields[user][position]" placeholder="Position">
        </div>
        <label class="col-sm-1 control-label ">Status</label>
        <div class="col-sm-2">
            <select style="width: 100%;" id="status"
                    name="fields[user][status]" class="required">
                        <?php
                        print_r($this->status);

                        foreach ($this->status as $status):
                            ?>
                    <option value="<?php echo $status['id_status'] ?>"><?php echo $status['status'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="btn btn-primary" id="save_user">Save</div>
            <div class="btn btn-primary clean">Clean Up</div>
        </div>
    </div>
</form>

<table class="datatable table table-primary datatable_motiv8"
       id="datatable_motiv8">
    <thead>
        <tr>
            <th width="20%">Full Name</th>
            <th width="20%">e-Mail</th>
            <th width="20%">Phone</th>
            <th width="20%">Position</th>
            <th width="10%">Status</th>
            <th width="10%"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (!empty($this->userList)) {
            foreach ($this->userList as $ul) :
                ?>
                <tr>
                    <td><?php echo $ul['fullname'] ?></td>
                    <td><?php echo $ul['user'] ?></td>
                    <td><?php echo $ul['phone'] ?></td>
                    <td><?php echo $ul['position'] ?></td>
                    <td><?php echo $ul['status_name'] ?></td>
                    <td><input type="hidden" id="id<?php echo $ul['id'] ?>"
                               name="id<?php echo $ul['id'] ?>"
                               value='<?php echo json_encode($ul); ?>'> <a
                               class="btn btn-circle btn-inverse btnjson" href="#"
                               id="<?php echo $ul['id'] ?>" alt="Edit"><i class="fa fa-pencil"></i></a></td>
                </tr>
                <?php
            endforeach
            ;
        }
        ?>
    </tbody>
</table>
