<script type="text/javascript">
    jQuery(document).ready(function() {
        $("#status option[value='1']").remove();
		$('select').select2();
		var limit_participants = <?php echo $this->licence_name['max_participants']!= ''? $this->licence_name['max_participants'] : 0; ?>;
		var total_participants = <?php echo count($this->participants_list); ?>;
		$('#totalP').html(total_participants);
		$('#limitP').html(limit_participants);
			
        $('#save_user').click(function() {			
			if((limit_participants > total_participants) || ($('#id_participant').val() != '')){
                    if ($('#frmUser').valid()) {
						if($('#su').val() == 0){
							$.post('<?php echo $this->baseUrl() ?>/client/participant/save/tabla/program_participants/idname/id_participant/idval/' + $("#id_participant").val(), $("#frmUser").serialize(), function(data) {
								if (data == 0) {
									alert("Error: Please try again");
								} else {
									alert("Information successfully saved");
									location.reload();
								}
							}); //fin function data					   
					} else {
						$('#msg').html('This email already exist, please verify the information.');
					} 
				}//end form  validation
			   } else {
			   		$('#msg').html('You have exceed the limit of participants, please contact the motive8 administrator.');
			   }//end qty validation
             }); //end save user.
			 

        $('.btnjson').click(            
                function() {                    
                    var idval = $(this).attr('id');                    
                    var data = jQuery.parseJSON($('#id' + idval).val());                    
                    $('#frmUser').populate(data);
					$('#msg').html('');
                    $('#password').val('');
                    $('#password').removeClass('required');
					$('#User_ID, #email').attr('disabled', true);
					$('select').change();
					$('#status').append($('<option>', { value: 1, text: 'Active' }));
                }); //end btnjson function.
				
				
        $('.clean').click(
                function() {
                    var form_id = $(this).closest("form").attr('id');
                    $('#' + form_id).trigger("reset");
                    $('#id_participant').val('');
					$('#User_ID, #email').attr('disabled', false);
					$('#msg').html('');
					$("#status option[value='1']").remove();
					$('select').change();
                }); //end clean form
 
	
	html =  $('#email').parent().html();
        html += " <span id='cd_user' class='error'></span>";
        $('#email').parent().html(html);
        $('#email').change(function(){
           $('#cd_user').html('Checking...');
           $.ajax({
              url: '<?php echo $this->baseUrl() ?>/admin/generico/checkgeneric/',
              dataType: 'json',
              data: {tb:'program_participants' , wr: 'id_licence = '+$('#id_licence').val()+' AND email ="'+$('#email').val()+'"' },
              success: function(response){			  
                  if(response.msg != 0){				  
				      $('#cd_user').html('This email already exist.'); 
					  $('#email').addClass('error');	
					  $("#su").val(1);			 
                  } else {
					 $('#cd_user').html('');
					 $('#email').removeClass('error');
					 $("#su").val(0);
					 $('#msg').html('');					 	
				  }
              }
            });
        });			
	
   }); //End ready function 		     
</script>
<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
        <h3 class="heading">Participant List (<a href="<?php echo $this->baseUrl() ?>/client/program/management/l/<?php echo $this->licence_name['id_licence'] ?>" ><?php echo $this->licence_name['name']; ?></a>)</h3>
  </div>
      <br/>
<!--FORM -->
<form class="form-horizontal" name="frmUser" id="frmUser"  method="POST">
    <input type="hidden" id="updated" name="fields[program_participants][updated]"  value="<?php echo date('Y-m-d H:m:s'); ?>"> 
    <input type="hidden" id="id_licence" name="fields[program_participants][id_licence]"  value="<?php echo $this->licence_name['id_licence']; ?>"> 
    <input type="hidden" id="id_participant" name="fields[program_participants][id_participant]" value=""> 
    <input type="hidden" id="id_client" name="fields[program_participants][id_client]" class="id_client" value="<?php echo $this->idClient; ?>">
    <input type="hidden" class="form-control"  id="password" name="fields[program_participants][password]" placeholder="Password" />
<input type="hidden" id="su" name="su" value="0"> 
    <div class="form-group">

        <label class="col-sm-2 control-label">User ID</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="User_ID" name="fields[program_participants][User_ID]" placeholder="User ID" >
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">First Name*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="first_name" name="fields[program_participants][first_name]" placeholder="First Name">
        </div>
        <label class="col-sm-2 control-label">Last Name*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="last_name"
                   name="fields[program_participants][last_name]" placeholder="Last Name">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">e-Mail*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required email" id="email"
                   name="fields[program_participants][email]" placeholder="e-Mail">
        </div>
        <label class="col-sm-2 control-label">Password</label>
        <div class="col-sm-2">
            Auto Generated when you send a Launch EDM.
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Company Code</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="company_code" name="fields[program_participants][company_code]" placeholder="Company Code">
        </div>

        <label class="col-sm-2 control-label">Company Name</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="company_name" name="fields[program_participants][company_name]" placeholder="Company Name">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Position*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="position" name="fields[program_participants][position]" placeholder="Position">
        </div>

        <label class="col-sm-2 control-label">Phone</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="phone" name="fields[program_participants][phone]" placeholder="Phone">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Mobile*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="mobile" name="fields[program_participants][mobile]" placeholder="Mobile">
        </div>

        <label class="col-sm-2 control-label">Address*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="address" name="fields[program_participants][address]" placeholder="Address">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Suburb*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="suburb" name="fields[program_participants][suburb]" placeholder="Suburb">
        </div>
        <label class="col-sm-2 control-label">State*</label>
        <div class="col-sm-2">
             <select  class="required" style="width: 100%;" id="state" name="fields[program_participants][state]">
                <?php foreach ($this->state as $state): ?>
                <option value="<?php echo $state['District'] ?>"><?php echo $state['District'] ?></option>
                <?php endforeach ?>
              </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Post Code*</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="postcode" name="fields[program_participants][postcode]" placeholder="Postcode">
        </div>
        <label class="col-sm-2 control-label stts">Status</label>
        <div class="col-sm-2">
            <select style="width: 100%;" id="status" name="fields[program_participants][status]" class="required">
                 <?php foreach ($this->status as $status): ?>
                    <option value="<?php echo $status['id_status'] ?>"><?php echo $status['status'] ?></option>
                <?php endforeach ?>
            </select>

        </div>        
    </div>    
    <div class="form-group">
   
        <div class="col-sm-offset-2 col-sm-10"><br/><br/>
        <span id='msg' class='error'></span><br/><br/>
            <a class="btn btn-primary" id="save_user" href="#" ><i class="fa fa-save"></i> Save</a>
            <div class="btn btn-primary clean"><i class="fa fa-eraser"></i> Clean Up</div>
             </div>
    </div>
</form>

<!-- Widget -->

	<div class="widget-body innerAll inner-2x"> 
    <h3>You have  <strong id="totalP"><?php echo count($this->participants_list); ?></strong> of <strong id="limitP"><?php echo $this->licence_name['max_participants']; ?></strong> Participants.</h3>
	  <!-- Table -->
		<table class="datatable table table-primary" id="datatable_motiv8">
			<thead>
				<tr>
					<th width="20%">Participant</th>
					<th width="20%">Email</th>
					<th width="20%">Position</th>
					<th width="20%">Address</th>
					<th width="10%">Status</th>
					<th width="10%"></th>
				</tr>
			</thead>
			<tbody>
        <?php foreach ($this->participants_list as $pl): ?>
        <tr>
					<td><?php echo $pl['first_name'] ?> <?php echo $pl['last_name'] ?></td>
					<td><?php echo $pl['email'] ?></td>
					<td><?php echo $pl['position'] ?></td>
					<td><?php echo $pl['address'] ?>, <?php echo $pl['suburb'] ?> <?php echo $pl['state'] ?>, <?php echo $pl['post_code'] ?></td>					
                    <td><?php echo $pl['status_name'] ?></td>
 					<td><input type="hidden" id="id<?php echo $pl['id_participant'] ?>" name="id<?php echo $pl['id_participant'] ?>" value='<?php echo json_encode($pl); ?>'> 
                        <div class="btn btn-circle btn-inverse btnjson" id="<?php echo $pl['id_participant'] ?>" alt="Edit"><i class="fa fa-pencil"></i></div>
                                        </td>                                        
				</tr>
        <?php endforeach ?>
      </tbody>
		</table>
		<!-- // Table END -->

	</div>


  </div>
</div>