<div class="row innerTB">
	<div class="col-md-12">
		<div class="separator"></div>
		<h2 class=" margin-none">Categories</h2>
		<br />
		<div class="row">
      <?php
						if (! empty ( $this->categories_list )) {
							foreach ( $this->categories_list as $sl ) :
								if (! empty ( $sl ['qty'] )) {
									?>
      <div class="col-sm-3 col-xs-12">
				<div class="widget widget-pinterest fixed-height"
					data-animate="bounceIn" data-delay="200">
					<div class="widget-body padding-none">
						<a
							href="<?php echo $this->baseUrl() ?>/catalog/shop/shop/ct/<?php echo $sl['id_category']; ?>/"
							class="thumb"> <img class="img-responsive"
							src="<?php echo $this->baseUrl() ?>/uploads/category/<?php echo $sl['image']; ?>"></a>
						<div class="description">
							<h5 class="text-uppercase"><?php echo $sl['category'] ?></h5>
							<span class="text-primary text-medium text-condensed"><?php echo $sl['qty'] ?></span>
						</div>
					</div>
				</div>
			</div>
      <?php
								
}
							endforeach
							;
						}
						?>
    </div>
		<!--END ROW-->
	</div>
</div>
