<h3 class="innerTB">Current Programs</h3>
<!-- Widget -->
<div class="widget">
    <div class="widget-body innerAll inner-2x">
        <!-- Table -->
        <table class="datatable dynamicTable table table-primary dataTable" id="programlist">
            <thead>
                <tr>
                    <th>Client</th>
                    <th>Program Name</th>
                    <th>Licence Type</th>
                    <th>From To</th>                    
                    <th>Status</th>
                    <th>Currency</th>
                    <th>Total<br>
Points<br>
Allocated</th>
                    <th>Total<br>
Points<br>
Redeemed</th>
                    <th>Total <br>
                    Invoiced</th>
                    <th>To<br>
Invoice</th>
                    <th>View<br>
Participant<br>
Site</th>
                    <th>Program<br>
Admin<br>
site</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->licencesList as $ll):  ?>                
                    <tr>                        
                        <td><?php echo $ll['clientNAme'] ?></td>
                        <td><?php echo $ll['name'] ?></td>
                        <td><?php echo $ll['licenceType'] ?></td>                        
                        <td align="center"><?php echo $ll['date_from'] .'<br/>'. $ll['date_to'] ?></td>
                        <td align="center"><?php echo $ll['status_name'] ?></td>                                                        
                        <td align="center"><?php echo $ll['points'] ?></td>                        
                        <td align="center"><?php echo $ll['totalAllocated'] ?></td>                        
                        <td align="center"><?php echo $ll['totalRedemption'] ?></td>                        
                        <td align="center"></td>                        
                        <td align="center"></td> 
                        <td align="center"><a class="btn btn-circle btn-inverse btnjson_licenses" href="<?php echo $this->baseUrl() ?>/participant/program/index/pg/1/l/<?php echo $ll['id_licence'] ?>"  title="Login as"  alt="Preview Participant site" target="_blank">
                                <i class="fa fa-eye"></i></a></td>
                        <td align="center"><a class="btn btn-circle btn-inverse btnjson_licenses" href="<?php echo $this->baseUrl() ?>/client/program/setup/licence/<?php echo $ll['id_licence'] ?>"  title="Login as"  alt="Preview Participant site" target="_blank">
                                <i class="fa fa-gear"></i></a></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <!-- // Table END -->

    </div>
</div>