<script type="text/javascript">
$(document).ready(function() {
  	 $('select').select2();   
	 $("#status").val("<?php echo $this->fullfilment_list[0]['status'] ?>"); 
	 $("#invoice").val("<?php echo $this->fullfilment_list[0]['invoice'] ?>"); 
	 $("#notes").val("<?php echo $this->fullfilment_list[0]['notes'] ?>"); 
	 $('select').change();
	 
$('#save').click(
    function () {
        if ($('#frmRedemption').valid()) {
            $.post('<?php echo $this->baseUrl() ?>/admin/generico/generico/tabla/program_redemtion/idname/id_redemption/idval/' + $("#id_redemption").val(), $("#frmRedemption").serialize(), function (data) {
                if (data != 0) {
                    alert("Information successfully saved");
					location.reload(true);					
                } else {
                    alert("Error: Please try again");
                }
            }); //fin function data
        }
    }); //end save function
});
</script>
<!-- Widget -->
<div class="widget">
  <div class="widget-body innerAll inner-2x">
   <form class="form-horizontal" name="frmRedemption" id="frmRedemption">
          <input type="hidden" id="id_redemption" name="fields[program_redemtion][id_redemption]" value="<?php echo $this->fullfilment_list[0]['id_redemption'] ?>">
          <input type="hidden" id="new_status_date" name="fields[program_redemtion][new_status_date]" value="<?php echo date('d-m-Y')?>">
    <table width="95%" align="center" class="table table-striped table-responsive swipe-horizontal table-primary">
            
			 <?php 
			 $grand_total = 0;
			    $gst =  ($this->fullfilment_list[0]['buy_price_gst'] + $this->fullfilment_list[0]['buy_freight_gst']);
			 	$total =  ($this->fullfilment_list[0]['buy_price_no_gst'] + $this->fullfilment_list[0]['buy_freight_no_gst'] + $gst) * $this->fullfilment_list[0]['qty'];
			  		 
			 ?>
				<!-- Cart item -->
				<tr>
				  <td width="25%" align="right" ><strong>Order #: </strong></td>
				  <td width="28%" ><?php echo $this->fullfilment_list[0]['ordernumber'] ?></td>
				  <td width="19%" align="right" ><strong>Client:</strong></td>
				  <td width="28%" ><?php echo  $this->fullfilment_list[0]['client'] ?></td>
		      </tr>
				<tr>
				  <td align="right" ><strong>Participant:</strong></td>
				  <td colspan="3" ><?php echo $this->fullfilment_list[0]['first_name'] ?> <?php echo $this->fullfilment_list[0]['last_name'] ?></td>
	    </tr>
				<tr>
				  <td align="right" ><strong>Address:</strong></td>
				  <td colspan="3" ><?php echo $this->fullfilment_list[0]['address'] ?>, <?php echo $this->fullfilment_list[0]['suburb'] ?>, <?php echo $this->fullfilment_list[0]['state'] ?>, <?php echo $this->fullfilment_list[0]['postcode'] ?></td>
	    </tr>
				<tr>
				  <td align="right" ><strong>Product: </strong></td>
				  <td colspan="3" ><?php echo $this->fullfilment_list[0]['name'] ?></td>
			  </tr>
				<tr>
				  <td align="right" ><strong>Issue date: </strong></td>
				  <td ><?php echo $this->fullfilment_list[0]['issue_date'] ?></td>
				  <td align="right" ><strong>Status: </strong></td>
				  <td ><?php echo $this->fullfilment_list[0]['status_name'] ?></td>
		      </tr>
				<tr>
				  <td align="right" ><strong>Supplier: </strong></td>
				  <td ><?php echo $this->fullfilment_list[0]['supplier'] ?></td>
				  <td align="right" ><strong><span style="width: 50px;">Qty: </span></strong></td>
				  <td ><?php echo $this->fullfilment_list[0]['qty'] ?></td>
		      </tr>
				<tr>
				  <td align="right" ><strong><span style="width: 80px;"> Price Exc: </span></strong></td>
				  <td ><?php echo number_format($this->fullfilment_list[0]['buy_price_no_gst'], 2) ?></td>
				  <td align="right" ><strong><span style="width: 80px;"> Freight Exc: </span></strong></td>
				  <td ><?php echo number_format($this->fullfilment_list[0]['buy_freight_no_gst'], 2) ?></td>
		      </tr>
				<tr>
				  <td align="right" ><strong><span style="width: 80px;">Price GST: </span></strong></td>
				  <td ><?php echo number_format($this->fullfilment_list[0]['buy_price_gst'], 2) ?></td>
				  <td align="right" ><strong><span style="width: 80px;">Freight GST</span></strong></td>
				  <td ><?php echo number_format($this->fullfilment_list[0]['buy_freight_gst'], 2) ?></td>
		      </tr>
				<tr>
				  <td align="right" ><strong>Total GST</strong></td>
				  <td ><?php echo number_format($gst, 2) ?></td>
				  <td align="right" ><strong><span style="width: 80px;">Total:</span></strong></td>
				  <td ><strong><?php echo number_format($total, 2) ?></strong></td>
	    </tr>
				<tr>
				  <td align="right" ><strong>Supplier Invoice: </strong></td>
				  <td ><input type="text" class="form-control required" id="invoice_s" name="fields[program_redemtion][invoice_s]"></td>
				  <td align="right" ><strong>Status:</strong></td>
				  <td ><select style="width: 100%;" id="status"	name="fields[program_redemtion][status]" class="required">
						<?php foreach ($this->status as $status): ?>
                        <option value="<?php echo $status['id_status'] ?>"><?php echo $status['status'] ?></option>
                        <?php endforeach ?>
                      </select>
</td>
	  </tr>
				<tr>
				  <td align="right" ><strong>Notes:</strong></td>
				  <td colspan="3" ><textarea name="fields[program_redemtion][notes]" id="notes" class="form-control"></textarea></td>
	  </tr>
				<tr>
				  <td align="right" >&nbsp;</td>
				  <td colspan="3" ><div class="btn btn-primary" id="save"><i class="fa fa-save"></i> Save</div></td>
	  </tr>
            

	  </table>
	  </form>

	</div>
</div>