<script type="text/javascript">
    jQuery(document).ready(function() {
		
	<?php if(!empty($this->user_detail)){ ?>
    $('#frmUser').populate( <?php echo Zend_Json::encode($this->user_detail); ?> );
	$("#password").val('');	
	<?php } ?>
	
        $('select').select2();
        $('#save_user').click(
                function() {
                    if ($('#frmUser').valid()) {
                        $.post('<?php echo $this->baseUrl() ?>/admin/user/save/tabla/user/idname/id/idval/' + $("#id").val(), $("#frmUser").serialize(), function(data) {
                            if (data == 0) {
                                alert("Error: Please try again");
                            } else {
                                alert("Information successfully saved");
                                $( "#frmUser" ).submit();
                            }
                        }); //fin function data
                    }
                }); //end save user.


    }); //End ready function      
</script>
<!-- col-app -->
<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
      <h4 class="heading">My Profile</h4>
    </div>
    <div class="widget-body innerAll inner-2x"> 

<form class="form-horizontal" name="frmUser" id="frmUser" action="<?php echo $this->baseUrl() ?>/user/profile/index/uid/<?php echo $this->user_detail['id'] ?>" method="POST">
    <input type="hidden" id="profile_id" name="fields[user][profile_id]" value="1"> 
    <input type="hidden"
           id="updated" name="fields[user][updated]"
           value="<?php echo date('Y-m-d H:m:s'); ?>"> <input type="hidden"
           id="id" name="fields[user][id]" value=""> 
    <input type="hidden" id="id_client" name="fields[user][id_client]" class="id_client" value="<?php echo $this->idClient; ?>">

    <div class="form-group">
        <label class="col-sm-2 control-label">Full Name</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="fullname"
                   name="fields[user][fullname]" placeholder="Full Name">
        </div>
        <label class="col-sm-1 control-label">Phone</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="phone"
                   name="fields[user][phone]" placeholder="Phone">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">e-Mail</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required email" id="user"
                   name="fields[user][user]" placeholder="e-Mail">
        </div>
        <label class="col-sm-1 control-label">Password</label>
        <div class="col-sm-2">
            <input type="password" class="form-control"
                   id="password" name="fields[user][password]"
                   placeholder="Password">

        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Position</label>
        <div class="col-sm-2">
            <input type="text" class="form-control required" id="position"
                   name="fields[user][position]" placeholder="Position">
        </div>
        <label class="col-sm-1 control-label ">Status</label>
        <div class="col-sm-2">
            <select style="width: 100%;" id="status"
                    name="fields[user][status]" class="required">
                        <?php
                        print_r($this->status);

                        foreach ($this->status as $status):
                            ?>
                    <option value="<?php echo $status['id_status'] ?>"><?php echo $status['status'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="btn btn-primary" id="save_user">Save</div>
        </div>
    </div>
</form>
    </div>
  </div>
</div>
<!-- // END col-app --