<script type="text/javascript">

jQuery(document).ready(function () {

$('#frmLicence').populate( <?php echo Zend_Json::encode($this->licence_detail); ?> );

	<?php if(empty($this->licence_detail['welcome_edm'])){ ?>
		$( "#welcome_ms").val("<p>Hi {$participant}</p><p>Edit and type in here the text for the email to launch your program to the database of participants you’ve loaded. It is important that your text invites participants to be part of your incentive and gives them a reason to log in to the website and learn about it. To make your email personal, do not delete the <em> &quot;Hi {$participant}&quot;</em> message on top of this box.</p><p>The details for your participant to log in are as follows. Don’t delete them from your email. This information will contain their own unique user name and password.</p><p style="color:blue">To log in to the Program Website use:<br>{$url}<br>User Name: {$user}<br>Password: {$password}</p><p>We also suggest you provide them herein with a phone number or an email to use in case they have any queries about your program criteria and close off with the program’s manager details.</p><p>Regards,<br>Motive8 team</p>");
	<?php } ?>
	
		<?php if(empty($this->licence_detail['invitation_edm_text'])){ ?>
		$( "#invitation_edm_text").val("<p>Edit and type in here the text for the email to launch your program to participants who need to register. It is important that your text invites participants and gives them a reason to register in your program.</p><p>Leave and don’t delete the following registration text in your email.</p><p>To register click here:<br>#url#</p><p>We also suggest you provide them herein with a phone number or an email to use in case they have any queries about your program criteria and close off with the program’s manager details.</p><p>Regards,<br>Motive8 team</p>");
	<?php } ?>
	
	
		<?php if(!empty($this->licence_detail['banner_edm'])){ ?>
		$(".bannerEDMLicence").html('<img  width="300" src="<?php echo $this->baseUrl() ?>/uploads/banner/<?php echo $this->licence_detail['banner_edm']; ?>"  />');		
		<?php } ?>
<?php if(!empty($this->saved)){ ?>
	alert('EDM Report: email sendt: '+<?php echo $this->saved; ?>+', Not Sent: '+<?php echo $this->not_saved; ?>);
<?php } ?>
	
$( ".CSVEDM" ).click(function() {
	$('#msg').html('');
	if($('#uploadedfile').val() != ''){
			$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
			var ext = $('#uploadedfile').val().split('.').pop().toLowerCase();					
				if($.inArray(ext, ['csv']) == -1) {
					alert('Invalid extension '+ext+'! just CSV Comma separated file is accepted');
					$.unblockUI();
				} else {
					$( "#frmLicence" ).submit();
				}
	} else {
		$('#msg').html('Please select a file.');
	}
});

	//invitation edm
$('#inv_edm').click(
    function () { 
			if ($('#test_to_inv').valid()) {			
				$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
				$.post('<?php echo $this->baseUrl() ?>/client/program/sendinv/', $("#frmLicence").serialize(), function (data) {
					if (data == 0) {
						alert("Error sending the test: Please try again");
					} else {
						alert("Your test was sent.");
						//location.reload();
					}
					$.unblockUI();
				}); //fin function data/**/				
			} //end validate
    }); //end invitation edm	
	
$('#test_edm_launch').click(
    function () { 
        if ($('#test_to').val() != '') {	
			$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
				$.post('<?php echo $this->baseUrl() ?>/client/program/sendedm/', $("#frmLicence").serialize(), function (data) {
					if (data == 0) {
						alert("Error sending the test: Please try again");
					} else {
						alert("Your test was sent.");
						//location.reload();
					}
					$.unblockUI();
				}); //fin function data/**/
		} else {
			$('#error_msg').html('Please enter "Send test to".');
		}
    }); //end save edm	

$('.launch_edm').click(
    function () { 	
	if(<?php echo $this->new_participant; ?> > 0){
        $(".launch_edm").confirm({
		text: "Please confirm that you want to send and email to all the new participants.",
		title: "Confirmation required",
		confirm: function(button) {		
			$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
            $.post('<?php echo $this->baseUrl() ?>/client/program/invitation/' , $("#frmEDM").serialize(), function (data) {
                if (data == 0) {
                    alert("Error: Please try again");
                } else {
                    alert("EDM successfully launched");
					location.reload();
                }
				$.unblockUI();
            }); //fin function data
        },
		cancel: function(button) {
			// do something
		},
		confirmButton: "Yes I am",
		cancelButton: "No",
		post: true
	});//end confirm
	} else {
		alert("Error: You don't have new participants");
	}
	
    }); //end save licenses	
	
	

$('#sentest_edm').click(
    function () {
		alert(); 
        if ($('#welcome_edm').val() != '' && $('#welcome_edm_title').val() != '' && $('#welcome_edm_from').val() != '' && $('#test_to').val() != '' ) {	
			if ($('#welcome_edm_from, #test_to').valid()) {		
			
				$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
				$.post('<?php echo $this->baseUrl() ?>/client/program/sendedm/', $("#frmLicence").serialize(), function (data) {
					if (data == 0) {
						alert("Error sending the test: Please try again");
					} else {
						alert("Your test was sent.");
						//location.reload();
					}
					$.unblockUI();
				}); //fin function data/**/
				
				
			} //end validate
		} else {
			$('#error_msg').html('All EDM fields are required.');
		}
    }); //end save edm	
	
tinymce.init({
        selector: "textarea.edm",
        plugins: [
                "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen jbimages media nonbreaking",
                "table contextmenu directionality emoticons template textcolor paste textcolor colorpicker textpattern"
        ],
        toolbar1: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect ",
        toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink code | forecolor",
        toolbar3: "table | hr removeformat | subscript superscript | charmap | visualchars ",
        menubar: false,
        toolbar_items_size: 'small',
		height : 200,
        style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],
		relative_urls: false
});

$('.save').click(
    function () { 
        if ($('#frmLicence').valid()) {			
			tinyMCE.triggerSave();
			$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
            $.post('<?php echo $this->baseUrl() ?>/admin/generico/generico/tabla/licenses/idname/id_licence/idval/' + $("#id_licence").val()+'/listvalues/0', $("#frmLicence").serialize(), function (data) {
                if (data == 0) {
                    alert("Error: Please try again");
                } else {
                    alert("Information successfully saved");
					location.reload();
                }
				$.unblockUI();
            }); //fin function data
        }
    }); //end save licenses	
	
	 var buttonedm = $('#upload_button_edm'), interval;
	 new AjaxUpload('upload_button_edm', {
        action: '<?php echo $this->baseUrl() ?>/plugins/upload_fullsize.php?imgname=<?php echo 'edm-'.$this->licence_detail['id_licence'].'-'.$this->licence_detail['client_id']; ?>&maxw=700&dir=banner',
		onSubmit : function(file , ext){
		if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
			// extensiones permitidas
			alert('Error: Just images jpg|png|jpeg|gif allowed');
			// cancela upload
			return false;
		} else {
			buttonedm.text('Loading...');
			this.disable();
		}
		},
		onComplete: function(file, response){
			buttonedm.text('Image loaded!');
			this.enable();	
			$('#banner_edm').val(response);		
			$(".bannerEDMLicence").html('<img  width="300" src="<?php echo $this->baseUrl() ?>/uploads/banner/'+response+'">');	
		}	
	});	//end upload image	
	
	 var buttonedm2 = $('#upload_button_edm2'), interval;
	 new AjaxUpload('upload_button_edm2', {
        action: '<?php echo $this->baseUrl() ?>/plugins/upload_fullsize.php?imgname=<?php echo 'edm-'.$this->licence_detail['id_licence'].'-'.$this->licence_detail['client_id']; ?>&maxw=700&dir=banner',
		onSubmit : function(file , ext){
		if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
			// extensiones permitidas
			alert('Error: Just images jpg|png|jpeg|gif allowed');
			// cancela upload
			return false;
		} else {
			buttonedm2.text('Loading...');
			this.disable();
		}
		},
		onComplete: function(file, response){
			buttonedm.text('Image loaded!');
			this.enable();	
			$('#banner_edm').val(response);		
			$(".bannerEDMLicence").html('<img  width="300" src="<?php echo $this->baseUrl() ?>/uploads/banner/'+response+'">');	
		}	
	});	//end upload image		

}); //End ready function
</script>
<form class="form-horizontal" name="frmLicence" id="frmLicence"  enctype="multipart/form-data" action="<?php echo $this->baseUrl() ?>/client/program/csvedm" method="POST">
<input type="hidden" id="id_licence" name="fields[licenses][id_licence]" value="<?php echo $this->licence_detail['id_licence']; ?>">
<input type="hidden" id="urlprogram" name="urlprogram" value="<?php echo $this->licence_detail['subdomain'].'.'.$_SESSION['siteurl']; ?>">
<input name="fields[licenses][banner_edm]" type="hidden" id="banner_edm" value="" />               
<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
      <h4 class="heading">Launch Email </h4>
    <span class="" style="float: right;font-weight: 700;font-size: 14px;">Dashboard (<a href="<?php echo $this->baseUrl() ?>/client/program/management/l/<?php echo $this->licence_detail['id_licence'] ?>" ><?php echo $this->licence_detail['name']; ?></a>)</span>        
    </div>
    <div class="widget-body innerAll inner-2x"> 
      <!-- Tabs -->
    
      <div class="relativeWrap" >
        <div class="box-generic"> 
          
          <!-- Tabs Heading -->
          <div class="tabsbar">
            <ul>
              <li class="glyphicons message_full active"><a href="#tab1-3" data-toggle="tab"><i></i> Uploaded participants </a></li>
              <li class="glyphicons message_empty"><a href="#tab2-3" data-toggle="tab"><i></i> Invitation Database </a></li>
            </ul>
          </div>
          <!-- // Tabs Heading END -->
          
            
            <!-- Tab content -->
             <div class="tab-content">   
            <div class="tab-pane active" id="tab1-3">
            
<div class="separator"></div>
<h4>Prepare program launch email to: uploaded participants</h4>
 <div class="form-group">
 <div class="separator"></div>
                    <label class="col-sm-3 control-label">Email header<br/><em style="font-size:10px;">Width 700px, Height 170px</em></label>
                    <div class="col-sm-8">
                      
                      <div class="btn btn-success" id="upload_button_edm">Upload Banner image</div>
                    </div>
              </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label"></label>
                    <div class="col-sm-8">
                      <div class="bannerEDMLicence"></div>
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-sm-3 control-label">Email Title</label>
                    <div class="col-sm-4">
                      <input name="fields[licenses][welcome_edm_title]" type="text" class="form-control" id="welcome_edm_title" placeholder="EDM Title" value=""  />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-sm-3 control-label">Email email from</label>
                    <div class="col-sm-4">
                      <input name="fields[licenses][welcome_edm_from]" type="text" class="form-control email" id="welcome_edm_from" placeholder="EDM email from" value=""  />
                    </div>
                  </div>
              <div class="form-group">
                    <label class="col-sm-3 control-label">Email Text </label>
                    <div class="col-sm-8">
                        <textarea name="fields[licenses][welcome_edm]" rows="5" class="form-control edm" id="welcome_edm" style="width: 100%;" placeholder="Here your welcome message..." ></textarea>
                      
                </div>
                </div>
                    
                      <div class="form-group ">
                    <label class="col-sm-3 control-label">Ensure your email contains the following details so that your participants can log into the program</label>
                  <div class="col-sm-6">
                      <strong>Program web addres</strong>: #url#<br/>
                        <strong>User</strong>: #username#<br/>
                        <strong>Password</strong>: #password#<br/>
                    </div>
              </div>
              
                  
                  <div class="form-group ">
                    <label class="col-sm-3 control-label"></label>
                  <div class="col-sm-6">
                      Before you test your email please save all changes 
                    </div>
              </div>
                  
                  <div class="form-group ">
                    <label class="col-sm-3 control-label">Sent test to</label>
                  <div class="col-sm-4">
                      <input name="test_to" type="text" class="form-control" id="test_to" placeholder="Sent test to" value=""  />
                    <em style="font-size:11px">Enter up to 5 addresses at once, separated by a comma.</em> 
                    </div>
                  </div>
                  
                  <div  style="color: #A40000; text-align:center;font-weight:bold;" id="error_msg"></div>
                  
                  <div class="separator"></div>
                  <div class="btn btn btn-success save"><i class="fa fa-save"></i> Save</div>
                  <div class="btn btn-primary" id="sentest_edm" ><i class="fa fa-envelope"></i> Send test</div>
                  <div class="btn btn btn-success launch_edm"><i class="fa  fa-check-square-o"></i>Launch Email</div>

           
            </div>


            <!-- Tab content -->
            <div class="tab-pane" id="tab2-3">
              <div class="separator"></div>
<h4>Prepare program launch email to: participants who need to register</h4>
                <div class="form-group">
            
            <div class="separator"></div>
                    <label class="col-sm-3 control-label">Email header<br/><em style="font-size:10px;">Width 700px, Height 170px</em></label>
                    <div class="col-sm-8">
                      <div  id="upload_button_edm2" iclass="btn btn-success">Upload Banner image</div>
                    </div>
              </div>
              <div class="form-group">
                    <label class="col-sm-3 control-label"></label>
                    <div class="col-sm-8">
                      <div class="bannerEDMLicence"></div>
                    </div>
                  </div>
              
                  <div class="form-group ">
                    <label class="col-sm-3 control-label">Email invitation title</label>
                    <div class="col-sm-4">
                      <input name="fields[licenses][invitation_edm_title]" type="text" class="form-control" id="invitation_edm_title" placeholder="EDM invitation title" value=""  />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label class="col-sm-3 control-label">Email from</label>
                    <div class="col-sm-4">
                      <input name="fields[licenses][invitation_edm_from]" type="text" class="form-control email" id="invitation_edm_from" placeholder="EDM email from" value=""  />
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Email invitation Text </label>
                    <div class="col-sm-8">
                      <div style="visibility: visible;" class="box-generic animated fadeInUp">
                        <textarea name="fields[licenses][invitation_edm_text]" rows="5" class="form-control edm" id="invitation_edm_text" style="width: 100%;" placeholder="EDM invitation Text..." ></textarea>
                      </div>
                    </div>
                  </div>
                 
                  <div  style="color: #A40000; text-align:center;font-weight:bold;" id="error_msg_inv"></div>
                  <div class="separator"></div>
                  <div class="media box-generic animated fadeInUp" style="visibility: visible;">
                <div class="form-group">
                  <label class="col-sm-3 control-label"></label>
                  <div class="col-sm-6" style="color:red"> The CSV file must contain a column called "email", will be use to launch the current EDM, the list will not be saved. </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">CSV file(Comma separated)</label>
                  <div class="col-sm-4">
                    <input type="hidden" name="MAX_FILE_SIZE" value="1000000" />
                    <input name="uploadedfile" id="uploadedfile" type="file" class="" />
                    <span id="msg" style="color:red"></span> </div>
                </div>
                 <div class="form-group ">
                    <label class="col-sm-3 control-label"></label>
                  <div class="col-sm-6">
                      Before you test your email please save all changes 
                    </div>
              </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Send test to</label>
                  <div class="col-sm-7">
                    <input name="test_to_inv" type="text" class="form-control " id="test_to_inv" placeholder="Sent test to" value=""  />
                    <em style="font-size:11px">Enter up to 5 addresses at once, separated by a comma.</em> </div>
                </div>
                
                <div class="form-group ">
                    <label class="col-sm-3 control-label"></label>
                  <div class="col-sm-6">
                     If you want to use another system to email participants to register, make sure you insert within your email your program website address: <?php echo $this->programurl ?>
                    </div>
              </div>
              
                <div class="clearfix"></div>
                <br/>
                 <div class="btn btn btn-success save"><i class="fa fa-save"></i> Save</div>
                <div class="btn btn-primary" id="inv_edm" ><i class="fa fa-envelope"></i> Send test </div>
                <div class="btn btn-success CSVEDM"><i class="fa fa-envelope-o"></i> Send Email</div>
            
            </div>
            
            </div>
            <!-- // Tab content END --> 
            
        </div>
      </div>
    </div>
    <!-- // Tabs END -->
      
      <div class="clearfix"></div>
      <br/>
      <br/>
      <!-- Table -->
      <table class="datatable table table-striped table-responsive swipe-horizontal table-primary">
        <!-- Table heading -->
        <thead>
          <tr>
            <th>Email Type</th>
            <th>Total Sent</th>
            <th>Total not sent</th>
            <th>Launch on</th>
          </tr>
        </thead>
        <!-- // Table heading END --> 
        <!-- Table body -->
        <tbody>
          <?php  foreach ($this->edm_list as $pl): ?>
          <!-- Table row -->
          <tr>
            <td><?php echo $pl['edm_type'] ?></td>
            <td><?php echo $pl['total_send'] ?></td>
            <td><?php echo $pl['total_notsend'] ?></td>
            <td><?php echo $pl['launch_date'] ?></td>
          </tr>
          <?php endforeach;  ?>
        </tbody>
        <!-- // Table body END -->
      </table>
      <!-- // Table END --> 
    </div>
  </div>
<!-- // END col-app --> 
  </form>
