<script type="text/javascript">
    jQuery(document).ready(function() {

$(".loadinfo").click(function(){	
		var id = $(this).attr('rel');
		$('#order-info').load('<?php echo $this->baseUrl();?>/client/program/orderdetails/id/'+id+'/l/<?php echo $this->licence_detail['id_licence'] ?>');
 });								
  	
	
   }); //End ready function 		     
</script>

<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
      <h3 class="heading">Orders Placed </h3>
      <span class="" style="float: right;font-weight: 700;font-size: 14px;">Dashboard (<a href="<?php echo $this->baseUrl() ?>/client/program/management/l/<?php echo $this->licence_detail['id_licence'] ?>" ><?php echo $this->licence_detail['name']; ?></a>)</span>        
    </div>
    <br/>
     
    <!-- Widget -->    
    <div class="widget-body innerAll inner-2x"> 
    <!-- Table -->
      <table class="datatable table table-striped table-responsive swipe-horizontal table-primary">        
        <!-- Table heading -->
        <thead>
          <tr>
          <th width="10%">ID</th>
          <th width="30%">Participant</th>
            <th width="15%">Order #</th>
            <th  width="15%">Status</th>
            <th  width="15%">Date</th>
            <th  width="15%">Points  Redeemed</th>
            <th></th>
          </tr>
        </thead>
        <!-- // Table heading END -->         
        <!-- Table body -->
        <tbody>
        <?php 
        if (!empty($this->ordersList)) {
            foreach ($this->ordersList as $pl) :
         ?> 
          <!-- Table row -->
          <tr>
          	<td><?php echo $pl['User_ID'] ?></td>
          	<td><?php echo $pl['participant'] ?></td>
            <td>LC<?php echo $this->id_licence; ?>OR<?php echo $pl['id'] ?></td>
            <td><?php echo $pl['status_name'] ?></td>
            <td><?php echo $pl['issue_date'] ?></td>
            <td align="center"><?php echo $pl['totalpoints'] ?></td>
            <td>
            <a href="#" data-toggle="modal" data-target="#OrdersPlaced" class="btn btn-circle btn-primary loadinfo" title="Review Order" rel="<?php echo $pl['id'] ?>" ><i class="fa fa-eye"></i></a>

            </td>
          </tr> 
        <?php endforeach;  } ?>                 
        </tbody>
        <!-- // Table body END -->        
      </table>
      <!-- // Table END -->    
    </div>
  </div>
</div>
