<script type="text/javascript">
    jQuery(document).ready(function() {

$(".loadinfo").click(function(){	
		var id = $(this).attr('rel');
		$('#order-info').load('<?php echo $this->baseUrl();?>/client/program/orderdetails/id/'+id+'/l/<?php echo $this->licence_detail['id_licence'] ?>');
 });								
  	
	
   }); //End ready function 		     
</script>

<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
      <h3 class="heading">Orders Placed </h3>
      <span class="" style="float: right;font-weight: 700;font-size: 14px;">Dashboard (<a href="<?php echo $this->baseUrl() ?>/client/program/management/l/<?php echo $this->licence_detail['id_licence'] ?>" ><?php echo $this->licence_detail['name']; ?></a>)</span>        
    </div>
    <br/>
     
    <!-- Widget -->    
    <div class="widget-body innerAll inner-2x"> 
   <a  target="_blank" href="<?php echo $this->baseUrl() ?>/client/program/download/l/<?php echo $this->licence_detail['id_licence'] ?>/r/2" class="btn btn-success " data-dismiss="fileupload"><i class="fa fa-download"></i> Download Report</a>
    <!-- Table -->
      <table class="datatable table table-striped table-responsive swipe-horizontal table-primary">        
        <!-- Table heading -->
        <thead>
          <tr>
          <th >Order #</th>
          <th >User ID</th>
          <th >Participant</th>  
          <th>Product</th>            
            <th>Status</th>
            <th>Date</th>
            <th>Points</th>
            <?php if($this->licence_detail['freight_to'] == 1){?>
            <th>Freight</th>
            <?php }?>
          </tr>
        </thead>
        <!-- // Table heading END -->         
        <!-- Table body -->
        <tbody>
        <?php 
        if (!empty($this->ordersList)) {
            foreach ($this->ordersList as $pl) :
         ?> 
          <!-- Table row -->
          <tr>
          	<td>LC<?php echo $this->id_licence; ?>OR<?php echo $pl['order_number'] ?></td>
          	<td><?php echo $pl['User_ID'] ?></td>
          	<td><?php echo $pl['participant'] ?></td>
            <td><?php echo $pl['name'] ?></td>            
            <td><?php echo $pl['status_name'] ?></td>
            <td><?php echo $pl['issue_date'] ?></td>
            <td><?php echo $pl['points'] ?></td>
            <?php if($this->licence_detail['freight_to'] == 1){?>
            <td><?php echo $pl['freight_cost'] ?></td>
            <?php }?>
            </td>
          </tr> 
        <?php endforeach;  } ?>                 
        </tbody>
        <!-- // Table body END -->        
      </table>
      <!-- // Table END -->    
    </div>
  </div>
</div>
