<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/flot/assets/lib/jquery.flot.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/flot/assets/lib/jquery.flot.resize.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/flot/assets/lib/plugins/jquery.flot.tooltip.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/flot/assets/custom/js/flotcharts.common.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/flot/assets/lib/jquery.flot.pie.js?v=v1.9.6&sv=v0.0.1"></script>
	<!-- Global -->
	<script>
(function($)
{
	if (typeof charts == 'undefined') 
		return;

	charts.chart_pie = 
	{
		// chart data
		data: [
			{ label: "Registered and Login",  data: <?php echo $this->num_logins ?> },
		    { label: "Registered and NOT Login",  data: <?php echo $this->num_notlogin; ?> },		    
		],
		// will hold the chart object
		plot: null,
		// chart options
		options: 
		{
			series: {
				pie: { 
					show: true,
					highlight: {
						opacity: 0.1
					},
					radius: 1,
					stroke: {
						color: '#fff',
						width: 2
					},
					startAngle: 2,
				    combine: {
	                    color: '#353535',
	                    threshold: 0.05
	                },
	                label: {
	                    show: true,
	                    radius: 1,
	                    formatter: function(label, series){
	                        return '<div class="label label-inverse">'+label+'&nbsp;'+Math.round(series.percent)+'%</div>';
	                    }
	                }
				},
				grow: {	active: false}
			},
			colors: [],
			legend:{show:false},
			grid: {
	            hoverable: true,
	            clickable: true,
	            backgroundColor : { }
	        },
	        tooltip: true,
			tooltipOpts: {
				content: "%s : %y.1"+"%",
				shifts: {
					x: -30,
					y: -50
				},
				defaultTheme: false
			}
		},
		
		placeholder: "#chart_pie",		
		// initialize
		init: function()
		{
			// apply styling
			charts.utility.applyStyle(this);			
			this.plot = $.plot($(this.placeholder), this.data, this.options);
		}
	};
	$(window).on('load', function(){
		setTimeout(function(){
			charts.chart_pie.init();
		}, 100);
	});

})(jQuery);
	</script>
<!-- col-app -->
<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
      <h4 class="heading">Reports (<a href="<?php echo $this->baseUrl() ?>/client/program/management/l/<?php echo $this->licence_detail['id_licence'] ?>" ><?php echo $this->licence_detail['name']; ?></a>)</h4>
    </div>
    <div class="widget-body innerAll inner-2x">
      
      <div class="col-sm-4" style="margin-bottom:10px;">
      	<div id="chart_pie" class="flotchart-holder"></div>
        Registred users: <?php echo $this->num_participant ?><br/> 
        Registred and Login: <?php echo $this->num_logins ?><br/>
      </div>
      
                  
       <div class="clearfix"></div> 
    
    </div>
  </div>
</div>
<!-- // END col-app --> 

