<script>
$(document).ready(function() {
$('select').select2();

$('#btnext').click(function () { 
		$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
		$.post('<?php echo $this->baseUrl() ?>/catalog/setup/washup', $("#frmCSV").serialize(), function (data) {
                if (data == 0) {
                    alert("Attencion: some of the fields have not been processed, please try again");
					 $( "#frmCSV" ).submit();
                } else {
					alert("Information successfully saved");
					//$.unblockUI();
                    $( "#frmCSV" ).submit();
                }
			});//fin function data
         });
		 
$('#btCategories').click(function () {
	
	 
	if ($('#frmCSV').valid()) {
		if($('input[type=checkbox]:checked').length == 0)
		{
			alert('Please select atleast one checkbox');
		} else {
			$.blockUI({ overlayCSS: { backgroundColor: '#252525' } });
			$.post('<?php echo $this->baseUrl() ?>/catalog/setup/savecategories', $("#frmCSV").serialize(), function (data) {
					if (data == 0) {
						alert("Error: Please try again,");
						 $( "#frmCSV" ).submit();
						$.unblockUI();
					} else {
						alert("Information successfully saved");
						$( "#frmCSV" ).submit();
					}
				});//fin function data
		}
	}//end validate
         });
		 
$('#id_category').change(function () {
	if( $('#id_category').val() != 0){
        $('#id_subcategory option').remove();
        $('#id_subcategory').change();
        $.post('<?php echo $this->baseUrl() ?>/admin/generico/getlistas', {
            pWhere: 'id_category ="' + $('#id_category').val() + '"',
            pTable: 'subcategories',
            pSelectid: 'id_subcategory',
            pSelectname: 'subcategory',
            pOrder: 'subcategory'
        }, function (data) {
            $.each(data, function (key, val) {
                $('#id_subcategory').append('<option value="' + val.value + '" >' + val.text + '</option>');
            });
            $('#id_subcategory').change();
        }, "json");
	} else {
		$('#id_subcategory').append('<option value="0">Ignore Category</option>');
	}
    });
	
	
    $('.checkall').on('click', function () {
		if($(this).prop("checked")) {
                $('.chkcls').prop('checked', true);
            } else {
                $('.chkcls').prop('checked', false);
            } 
        
    });
		 
});
</script>
<style>
.footerFloadButton {
	background-position: top;
	padding: 0px 30px 30px 0px;
	position: fixed;
	right: 40px;
	bottom: 10px;
}
</style>
<div class="wizard">
	<h3 class="innerTB">Catalogue Wash</h3>
	<div class="widget-body">
		<div class="col-sm-12">
      <?php
						foreach ( $this->wash_qty as $wql ) :
							?>
      <div class="col-md-3">
				<a
					href="<?php echo $this->baseUrl() ?>/catalog/catalog/index/status/<?php echo $wql['status']; ?>">
					<div
						class="widget-stats widget-stats-inverse widget-stats-1 animated fadeInDown"
						style="visibility: visible;">
						<span
							class="glyphicons <?php if($wql['status']=='Enabled'){ echo 'check'; } else { echo 'unchecked'; }  ?> ">
							<i></i> <span class="txt"><?php echo $wql['status']; ?> Products</span>
						</span>
						<div class="clearfix"></div>
						<span class="count"><?php echo $wql['total']; ?></span>
					</div>
				</a>
			</div>
      <?php endforeach; ?>
      <div class="col-md-3">
				<a href="<?php echo $this->baseUrl() ?>/catalog/shop">
					<div
						class="widget-stats widget-stats-inverse widget-stats-1 animated fadeInDown"
						style="visibility: visible;">
						<span class="glyphicons tag"> <i></i> <span class="txt">Catalog
								Categories</span>
						</span>
						<div class="clearfix"></div>
						<span class="count"><?php echo $this->cat_qty['total_cat']; ?></span>
					</div>
			
			</div>
			</a>
			<div class="col-md-3">
				<a href="<?php echo $this->baseUrl() ?>/catalog/shop">
					<div
						class="widget-stats widget-stats-inverse widget-stats-1 animated fadeInDown"
						style="visibility: visible;">
						<span class="glyphicons tags"> <i></i> <span class="txt">Catalog
								Subcategories</span>
						</span>
						<div class="clearfix"></div>
						<span class="count"><?php echo $this->sub_qty['total_subcat']; ?></span>
					</div>
				</a>
			</div>
			<!-- <div class="col-md-3">
        <div class="widget-stats widget-stats-inverse widget-stats-1 animated fadeInDown" style="visibility: visible;"> <span class="glyphicons circle_ok"> <i></i> <span class="txt">Subcategories Included CSV</span> </span>
          <div class="clearfix"></div>
          <span class="count"><?php echo $this->qty_added['qty']; ?></span> </div>
      </div>-->
			<div class="col-md-3">
				<a
					href="<?php echo $this->baseUrl() ?>/catalog/setup/index/ignored/1">
					<div
						class="widget-stats widget-stats-inverse widget-stats-1 animated fadeInDown"
						style="visibility: visible;">
						<span class="glyphicons circle_minus"> <i></i> <span class="txt">Subcategories
								Ignored CSV</span>
						</span>
						<div class="clearfix"></div>
						<span class="count"><?php echo $this->qty_ignored['qty']; ?></span>
					</div>
			
			</div>
			</a>
		</div>
		<form class="form-horizontal" name="frmCSV" id="frmCSV"
			action="<?php echo $this->baseUrl() ?>/catalog/setup" method="POST">
			<div class="form-group">
        <?php
								if (! empty ( $this->subcat_list )) {
									?>
        <div class="col-sm-12">
					<div class="widget widget-heading-simple widget-body-white">
						<div class="lead innerTB">
							<p>New Categories</p>
						</div>
						<table border="1" class="table-primary" id="products_motiv8"
							align="center" style="width: 50%">
							<thead>
								<tr>
									<th>Category</th>
									<th>Subategory</th>
								</tr>
								<tr>
									<th width="50%"><select style="width: 100%;" id="id_category"
										name="id_category" class="required">
											<option value="">--</option>
											<option value="0">Ignore Category</option>
                    <?php foreach ($this->cat_select as $ct): ?>
                    <option value="<?php echo $ct['id_category']; ?>"><?php echo $ct['category']; ?></option>
                    <?php endforeach ?>
                  </select></th>
									<th width="50%"><select style="width: 100%;"
										id="id_subcategory" name="id_subcategory" class="required">
											<option value="">--</option>
									</select></th>
								</tr>
							</thead>
							<tbody>
								</tr>
								<tr>
									<td colspan="2" style="background-color: #FFE6E6"><input
										type="checkbox" name="checkall" id="checkall" value="1"
										class="checkall"> **Select All</td>
                  <?php
									$i = 0;
									foreach ( $this->subcat_list as $sl ) :
										?>
                
								
								
								<tr>
									<td><input type="checkbox" name="subcat[<?php echo $i; ?>]"
										id="subcat[<?php echo $i; ?>]" value="1" class="chkcls">
                    <?php echo $sl['category']?>
                  <input type="hidden" id="csvcategory"
										name="csvcategory[<?php echo $i; ?>]"
										value="<?php echo $sl['category'] ?>"></td>
									<td><?php echo $sl['subcategory']?>
                  <input type="hidden" id="csvsubcategory"
										name="csvsubcategory[<?php echo $i; ?>]"
										value="<?php echo $sl['subcategory'] ?>"></td>
								</tr>
                <?php
										$i = $i + 1;
									endforeach
									;
									?>
              </tbody>
						</table>
						<div class="separator bottom footerFloadButton">
							<div id="btCategories" class="btn btn-primary ">Update Categories</div>
						</div>
					</div>
				</div>
        <?php  } else {?>
        <!--Wash up satatus-->
				<div class="col-sm-6">
          <?php if($this->wash_list['total_rows'] != 0){ ?>
          <div class="widget widget-heading-simple widget-body-white">
						<div class="widget-body innerAll inner-2x">
							<div class="innerL">
								<div class="separator bottom"></div>
								<div class="glyphicons glyphicon-large database_plus">
									<i></i>
									<div class="lead center innerTB">
										<p>
											<strong><?php echo $this->wash_list['total_rows']; ?></strong>
											Products to <strong>update</strong> or <strong>insert</strong>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="separator bottom"></div>
					<div id="btnext" class="btn btn-primary">Wash Catalogue</div>
          <?php  } else {?>
          <div class="widget widget-heading-simple widget-body-white">
						<div class="widget-body innerAll inner-2x">
							<div class="innerL">
								<div class="separator bottom"></div>
								<div class="glyphicons glyphicon-large disk_saved">
									<i></i>
									<div class="lead center innerTB">
										<p>Database up to date</p>
									</div>
								</div>
							</div>
						</div>
					</div>
          <?php  } ?>
        </div>
				<!--END Wash up satatus-->
				<div class="col-sm-6">
					<div class="widget widget-heading-simple widget-body-white">
						<div class="widget-body innerAll inner-2x">
							<div class="innerL">
								<div class="separator bottom"></div>
								<div class="glyphicons glyphicon-large sampler">
									<i></i>
									<div class="lead center innerTB">
										<p>Categories up to date</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
        <?php  } ?>
      </div>
		</form>
	</div>
</div>
