       <form name="formLogin" id="formLogin" action="" method="post" class="form-horizontal row-fluid">
      <label class="error" for="cname2" generated="true" style="display: block;"> <?php if(!empty($this->message)) echo 'Incorrect username or password 5.';?></label>
        <p>
        <input type="text" name="username" id="username" placeholder="User Name"  class="row-fluid" value=""></p>
        <p><input type="password" name="password" id="password" placeholder="Password"  class="row-fluid" value=""></p>
        <p class="remember_me">
          <label>
            <input type="checkbox" name="remember_me" id="remember_me">
            Remember me on this computer
          </label>
        </p>
        <p class="submit"><input type="submit" name="commit" value="Login"></p>
      </form>