<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 footer-sticky navbar-sticky"> <![endif]-->
<!--[if gt IE 8]> <html class="ie footer-sticky navbar-sticky"> <![endif]-->
<!--[if !IE]><!-->
<html class="footer-sticky navbar-sticky">
<!-- <![endif]-->
<head>
<title>motive8</title>

<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<?php 
/*This line outputs the doctype we set in the bootstrap */
$registry         = Zend_Registry::getInstance();
$auth             = Zend_Auth::getInstance();
$user             = $auth->getIdentity();
$genObj       	   =new Default_Model_Generico();		
$client 	= $genObj->getRow("id_client=".$user['id_client'], "client");
?>
<script type="text/javascript">
	var base_url    = '<?php echo $this->baseUrl() ?>';
	var site_url    = '<?php echo $this->url() ?>';
</script>
<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
   
<link rel="stylesheet/less" href="<?php echo $this->baseUrl() ?>/assets/less/admin/module.admin.stylesheet-complete.layout_fixed.true.less" /> -->
<!--
[if lt IE 9]><link rel="stylesheet" href="../assets/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/assets/css/admin/module.admin.stylesheet-complete.layout_fixed.true.min.css" />
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/jquery/jquery.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.validate.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/AjaxUpload.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/modernizr/modernizr.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/less-js/less.min.js?v=v1.9.6&sv=v0.0.1"></script>

</head>
<body class=" menu-right-hidden">
<!-- Main Container Fluid -->
<div class="container-fluid menu-hidden">
<!-- Content -->
<div id="content">
<div class="navbar hidden-print main navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header"><img src="<?php echo $this->baseUrl() ?>/uploads/logo/<?php echo $client['logo']; ?>" alt="" class="img-clean" height="40px" style="margin-top:10px; "></div>
    <div class="navbar-collapse collapse">
      <div class="col-md-3 visible-md visible-lg pull-right padding-none">
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown dropdown-light"> <a href="" data-toggle="dropdown" class="dropdown-toggle"><?php echo $client['client']; ?>: <?php echo $user['fullname']; ?><span class="caret"></span></a>
              <ul class="dropdown-menu pull-left">
                <li><a href="<?php echo $this->baseUrl() ?>/user/profile/index/uid/<?php echo $user['id']; ?>/ly/client" class="glyphicons user"><i></i>My Profile</a></li>
                <li><a id="logout" onClick="ConfirmarSalir();" href="#" class="glyphicons lock"><i></i>Logout</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- // END navbar -->
<div id="menu-top" class="menu-top-inverse" style="background-color:<?php echo $client['bg']; ?>">
  <div class="container">
    <ul class="main pull-left">
    <li class="dropdown"> <a class="" href="<?php echo $this->baseUrl() ?>/client"> <i class="fa fa-fw fa-home"></i> Home </a></li> 
    <!--     
    <li class="dropdown"> <a data-toggle="dropdown" class="dropdown-toggle" href=""><i class="fa fa-fw fa-cog"></i> Settings <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="active"><a href="<?php echo $this->baseUrl() ?>/admin/client/editclient/id/<?php echo $client['id_client']; ?>" class="no-ajaxify"><?php echo $client['client']; ?> Profile</a></li>
        </ul>
      </li>-->
    </ul>
    </li>
    </ul>
  </div>
</div>
<div class="layout-app">
  <div class="container"><!-- row-app -->
    <div class="row row-app"> 
      <!-- col -->
      <div class="col-md-12 col-sm-12"> 
        <!-- col-separator.box -->
        <div class="col-separator col-unscrollable box">
          <div id="contenido"><?php echo $this->layout()->content ?></div>
        </div>
        <!-- // END row-app --> 
      </div>
    </div>
  </div>
  <!-- // Content END -->
  <div class="clearfix"></div>
  <!-- // Sidebar menu & content wrapper END --> 
  <!-- Footer -->
  <div id="footer" class="hidden-print"> 
    <!--  Copyright Line -->
    <div class="copy">&copy; 2014 <a href="http://www.motive8.com.au">motive8</a> - All Rights Reserved. <a href="http://ad-inc.com.au" target="_blank">AD+INC</a></div>
    <!--  End Copyright Line --> 
  </div>
  <!-- // Footer END --> 
</div>
<!-- // Main Container Fluid END --> 
<!-- Global --> 
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/assets/js/jquery.populate.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/bootstrap/js/bootstrap.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/breakpoints/breakpoints.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/core.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/animations.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-select/assets/lib/js/bootstrap-select.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/select2/assets/lib/js/select2.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/colorpicker-farbtastic/assets/js/farbtastic.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-datepicker/assets/lib/js/bootstrap-datepicker.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-datepicker/assets/custom/js/bootstrap-datepicker.init.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/lib/js/jquery.dataTables.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/custom/js/DT_bootstrap.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.blockUI.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/common.js"></script>
<script type="text/javascript">
    function ConfirmarSalir()
    {
		window.location = "<?php echo $this->baseUrl() ?>/login/logout";
								
     }

</script>
</body>
</html>