<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 footer-sticky navbar-sticky"> <![endif]-->
<!--[if gt IE 8]> <html class="ie footer-sticky navbar-sticky"> <![endif]-->
<!--[if !IE]><!-->
<html class="footer-sticky navbar-sticky">
<!-- <![endif]-->
<head>
<title>motive8</title>

<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<?php 
/*This line outputs the doctype we set in the bootstrap */
$registry         = Zend_Registry::getInstance();
$auth             = Zend_Auth::getInstance();
$user             = $auth->getIdentity();
$genObj       	  = new Default_Model_Generico();

$client 	= $genObj->getRow("id_client='".$user['id_client']."'", "client");
$licence 	= $genObj->getRow("id_licence='{$this->id_licence}'", "licenses");
?>
<script type="text/javascript">
	var base_url    = '<?php echo $this->baseUrl() ?>';
	var site_url    = '<?php echo $this->url() ?>';
</script>
<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
   
<link rel="stylesheet/less" href="<?php echo $this->baseUrl() ?>/assets/less/admin/module.admin.stylesheet-complete.layout_fixed.true.less" /> -->
<!--
[if lt IE 9]><link rel="stylesheet" href="../assets/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/assets/css/admin/participant.css" />
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/jquery/jquery.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.validate.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/AjaxUpload.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/modernizr/modernizr.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/less-js/less.min.js?v=v1.9.6&sv=v0.0.1"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/assets/css/cssmenu-2/styles.css">
<script src="<?php echo $this->baseUrl() ?>/assets/css/cssmenu-2/script.js"></script>
</head>
<style type="text/css">
.divbanner {
	border: 2px solid;
	border-top-left-radius: 1em;
	border-top-right-radius: 1em;
	padding: 0px;
}

.navbar {
	-webkit-border-radius: 0 0 0 0;
	-moz-border-radius: 0 0 0 0;
	border-radius: 0 0 0 0;
	border: none;
	border-bottom: 1px solid <?php echo $licence['color_bg']; ?>;
	/*background: #fff*/
}

.backgraundImage {
	
 <?php if($licence['bg_image'] == 'Apple-Prods.png') { ?> 
	background-image: url(<?php echo $this->baseUrl();?>/uploads/bg_licences/<?php echo $licence['bg_image'];?>);
 	background-repeat: no-repeat;
	background-position: center;	
 <?php } else if($licence['bg_image'] == 'None') { ?> 
 
 <?php } else { ?> 
    background-image: url(<?php echo $this->baseUrl(); ?>/uploads/bg_licences/<?php echo $licence['bg_image'] ?>);
	background-repeat: repeat;
	background-position: center;
	width: 100%;
	height: 100%;
 <?php } ?> 
	 background-color: <?php echo $licence['color_bg']; ?>;
	 -webkit-background-size: cover;
	 -moz-background-size: cover;
	 -o-background-size: cover;/*background-size:100%;*/
}

.divshadow {
    box-shadow: 0px 5px 5px 5px #888888;
}

.divshadow2 {
    box-shadow: 0px 3px 15px 3px #888888;
}

</style>
<body class=" menu-right-hidden backgraundImage"  >

<!-- Main Container Fluid -->
<div class="container-fluid menu-hidden"> 
  <!-- Content -->
  <div id="content"  >
  
    <div class="navbar hidden-print main navbar-default" role="navigation" style="height:100%; border-color: transparent">
      <div class="container" style="padding-left:0px; padding-right:0px">
        <?php if (!empty( $licence['banner'])) { ?>
            <div style="z-index:1000; margin-top:15px;"  > 
                <img src="<?php echo $this->baseUrl() ?>/uploads/banner/<?php echo $licence['banner']; ?>" alt="" class="divbanner" style="width:100%; max-height:185px"  > 
            </div>
        <?php } else { ?>
            <div class="navbar-header" >
                <img src="<?php echo $this->baseUrl() ?>/uploads/logo/<?php echo $client['logo']; ?>" alt="" class="img-clean" height="40px" style="margin-top:10px; ">
            </div>
        <?php } ?>
      </div>
    </div>
    
    <div id="menu-top" class="menu-top-inverse" style="background-color:none;">
      <div class="container">
        <div id="cssmenu">
          <ul>
            <li class="active" id="pg1"> <a class="" href="<?php echo $this->baseUrl() ?>/participant/program/index/pg/1">Home </a></li>
            <li id="pg2"> <a  class="" href="<?php echo $this->baseUrl() ?>/participant/program/index/pg/2">Criteria </a></li>
            <li id="pg3"> <a  href="<?php echo $this->baseUrl() ?>/participant/program/rewards/l/<?php echo $licence['id_licence']; ?>">Rewards </a></li>
            <li style=" float:right"><a id="logout" onClick="ConfirmarSalir();" href="#">Logout </a></li>            
          </ul>
          
        </div>
      </div>
    </div>
    <!-- // END navbar -->
    
    <div class="layout-app "  >
      <div class="container" >
        <div class="row row-app margin-none divshadow"   style="background-color:#fff;min-height:650px;" >
          <div id="contenido" ><?php echo $this->layout()->content ?></div>
        </div>
      </div>
    </div>
    
 
  
  <div class="container ">
    <div class="footer divshadow2">&copy; <?php echo date('Y') ?> <a href="http://www.motive8.com.au" target="_blank">motive8</a> - All Rights Reserved. <a href="http://ad-inc.com.au" target="_blank">AD+INC</a> 
    </div>
  </div><!-- // container footer END --> 


<!-- Modal -->
<div class="modal fade" id="WishList" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">My Shopping Cart</h4>
      </div>
      <div  class="modal-body" id="order-detail">
    
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="ProductDetail" tabindex="-1" role="dialog" aria-labelledby="ProductDetaillLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Product Detail</h4>
      </div>
      <div class="modal-body" id="product-detail">
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="OrdersPlaced" tabindex="-1" role="dialog" aria-labelledby="OrdersPlacedLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Product Detail</h4>
      </div>
      <div class="modal-body" id="order-info">
      </div>
    </div>
  </div>
</div>
 
  </div><!-- // Content END --> 
 </div><!-- Main Container Fluid END-->
 


<!-- Global --> 
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/assets/js/jquery.populate.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/bootstrap/js/bootstrap.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/lazyload.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/breakpoints/breakpoints.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/core.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/animations.init.js?v=v1.9.6"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-select/assets/lib/js/bootstrap-select.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/select2/assets/lib/js/select2.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/colorpicker-farbtastic/assets/js/farbtastic.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-datepicker/assets/lib/js/bootstrap-datepicker.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/lib/js/jquery.dataTables.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/custom/js/DT_bootstrap.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.blockUI.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/common.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery-ui.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/notifications/notyfy/assets/lib/js/jquery.notyfy.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.numeric.js"></script>
<script type="text/javascript">
   
    function ConfirmarSalir()
    {
		window.location = "<?php echo $this->baseUrl() ?>/login/logout";
								
     }
	 
jQuery(document).ready(function () {

$(".close").click(function(){		
	$('#product-detail').html('');
});
 	
 if(<?php echo $this->page !='' ? $this->page:0 ?> == 1 ){
	 $('#pg1').addClass('active');
	 $('#pg2').removeClass('active');
	 $('#pg3').removeClass('active');
	 } else if(<?php echo $this->page !='' ? $this->page:0 ?> == 2 ){
	 $('#pg2').addClass('active');
	 $('#pg1').removeClass('active'); 
	 $('#pg3').removeClass('active');
	} else if(<?php echo $this->page !='' ? $this->page:0 ?> == 3 ){
	 $('#pg3').addClass('active');
	 $('#pg1').removeClass('active'); 
	 $('#pg2').removeClass('active');
	} else {
	 $('#pg3').removeClass('active');
	 $('#pg1').removeClass('active'); 
	 $('#pg2').removeClass('active');
	}

});

</script>
</body>
</html>