<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 app sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 app sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 app sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if gt IE 8]> <html class="ie app sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky"> <![endif]-->
<!--[if !IE]><!-->
<html class="sidebar sidebar-fusion sidebar-kis footer-sticky navbar-sticky">
<!-- <![endif]-->
<head>
<title>motive8</title>
<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<?php
        /* This line outputs the doctype we set in the bootstrap */
        $registry = Zend_Registry::getInstance();
        $auth = Zend_Auth::getInstance();
        $user = $auth->getIdentity();
        $genObj = new Default_Model_Generico();

        $lstConf = $genObj->getMenu($where = "a.group='CNT' AND a.status=1 AND c.id=".$user['profile_id']);
        $lstCatalog = $genObj->getMenu($where = "a.group='CTL' AND a.status=1 AND c.id=".$user['profile_id']);
        $lstSettings = $genObj->getMenu($where = "a.group='STT' AND a.status=1 AND c.id=".$user['profile_id']);
        $client = $genObj->getRow("id_client=".$user['id_client'], "client");
        ?>
<script type="text/javascript">
            var base_url = '<?php echo $this->baseUrl() ?>';
            var site_url = '<?php echo $this->url() ?>';
        </script>
<!-- 
                **********************************************************
                In development, use the LESS files and the less.js compiler
                instead of the minified CSS loaded by default.
                **********************************************************
                <link rel="stylesheet/less" href="<?php echo $this->baseUrl() ?>/assets/less/admin/module.admin.stylesheet-complete.sidebar_type.fusion.less" />-->

<!--[if lt IE 9]><link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/assets/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/assets/css/admin/module.admin.stylesheet-complete.sidebar_type.fusion.min.css" />
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
              <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
            <![endif]-->

<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery-1.7.1.min.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.validate.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/AjaxUpload.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.crypt.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/jquery/jquery-migrate.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/modernizr/modernizr.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/less-js/less.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/flot/assets/lib/excanvas.js?v=v1.9.6&sv=v0.0.1"></script>
<script>if (/*@cc_on!@*/false && document.documentMode === 10) {
                document.documentElement.className += ' ie ie10';
            }</script>
</head>
<body class=" menu-right-hidden">
<!-- Main Container Fluid -->
<div class="container-fluid menu-hidden"> 
  <!-- Main Sidebar Menu -->
  <div id="menu" class="hidden-print hidden-xs sidebar-blue sidebar-brand-primary">
    <div id="sidebar-fusion-wrapper">
      <div id="brandWrapper"> <a href="index.html?lang=en" class="display-block-inline pull-left logo"><img src="<?php echo $this->baseUrl() ?>/assets/images/logo/app-logo-style-default.png" alt=""></a> </div>
      <ul class="menu list-unstyled" id="navigation_current_page">
        <li class=""><a href="<?php echo $this->baseUrl() . '/admin'  ?>"  ><i class="fa fa-home"></i><span>Home Page</span></a></li>
        <?php if (empty($lstConf) === false): ?>
        <li class="hasSubmenu"><a href="#sidebar-fusion-contacts" data-toggle="collapse" class="glyphicons parents"><i></i><span>Client Managment</span></a>
          <ul class="collapse" id="sidebar-fusion-contacts">
            <?php foreach ($lstConf as $row): ?>
            <li><a class="glyphicons <?php echo $row['icon'] ?>" href="<?php echo $this->baseUrl() ?>/<?php echo $row['url'] ?>"><i></i><span><?php echo $row['option_name'] ?></span></a></li>
            <?php endforeach; ?>
          </ul>
        </li>
        <?php endif; ?>
        <?php if (empty($lstCatalog) === false): ?>
        <li class="hasSubmenu"><a href="#sidebar-fusion-catalogue" data-toggle="collapse" class="glyphicons sampler"><i></i><span>Catalogue</span></a>
          <ul class="collapse" id="sidebar-fusion-catalogue">
            <?php foreach ($lstCatalog as $row): ?>
            <li><a class="glyphicons <?php echo $row['icon'] ?>" href="<?php echo $this->baseUrl() ?>/<?php echo $row['url'] ?>" target="<?php echo $row['target'] ?>"><i></i><span><?php echo $row['option_name'] ?></span></a></li>
            <?php endforeach; ?>
          </ul>
        </li>
        <?php endif; ?>
        <?php if (empty($lstSettings) === false): ?>
        <li class="hasSubmenu"><a href="#sidebar-fusion-settings" data-toggle="collapse" class="glyphicons user"><i></i><span>Settings</span></a>
          <ul class="collapse" id="sidebar-fusion-settings">
            <?php foreach ($lstSettings as $row): ?>
            <li><a class="glyphicons <?php echo $row['icon'] ?>" href="<?php echo $this->baseUrl() ?>/<?php echo $row['url'] ?>" target="<?php echo $row['target'] ?>"><i></i><span><?php echo $row['option_name'] ?></span></a></li>
            <?php endforeach; ?>
          </ul>
        </li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
  <!-- // Main Sidebar Menu END --> 
  
  <!-- Content -->
  <div id="content">
    <div class="navbar hidden-print navbar-inverse box main" role="navigation">
      <ul class="notifications pull-left hidden-xs">
        <li class="dropdown notif"> <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="notif-block fa fa-bell-o"></i><span class="badge badge-white">0</span></a> </li>
      </ul>
      <div class="user-action pull-right menu-right-hidden-xs menu-left-hidden-xs">
        <div class="dropdown username hidden-xs pull-left"> <a class="dropdown-toggle " data-toggle="dropdown" href="#"> <span class="media margin-none"><span class="media-body"> <?php echo $client['client']; ?>: <?php echo $user['fullname']; ?> <span class="caret"></span> </span> </span> </a>
          <ul class="dropdown-menu pull-right">
            <li><a href="<?php echo $this->baseUrl() ?>/user/profile/index/uid/<?php echo $user['id']; ?>/ly/admin" class="glyphicons user"><i></i> Profile</a></li>
            <li><a id="logout" onClick="ConfirmarSalir();" href="#" class="glyphicons lock"><i></i>Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- // END navbar --> 
    <!-- col -->
    <div class="col-md-12"> 
      <!-- Widget -->
      <div class="widget">
        <div class="widget-body innerAll inner-2x" id="load_content"> <?php echo $this->layout()->content ?></div>
        <!--end div contenido--> 
        
      </div>
      <!-- // Widget END --> 
    </div>
    <!-- // END col --> 
  </div>
</div>
<!-- // Main Container Fluid END --> 
<script data-id="App.Config">
            var basePath = '',
                    commonPath = '<?php echo $this->baseUrl() ?>/assets/',
                    rootPath = '../',
                    DEV = false,
                    componentsPath = '<?php echo $this->baseUrl() ?>/assets/components/',
                    layoutApp = true,
                    module = 'admin';

            var primaryColor = '#87c844',
                    dangerColor = '#b55151',
                    successColor = '#609450',
                    infoColor = '#4a8bc2',
                    warningColor = '#ab7a4b',
                    inverseColor = '#45484d';

            var themerPrimaryColor = primaryColor;
        </script> 
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/assets/js/jquery.populate.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/bootstrap/js/bootstrap.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/nicescroll/jquery.nicescroll.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/breakpoints/breakpoints.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/preload/pace/pace.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/preload.pace.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/gallery/blueimp-gallery/assets/lib/js/blueimp-gallery.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/gallery/blueimp-gallery/assets/lib/js/jquery.blueimp-gallery.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/image-preview/image-preview.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/sidebar.main.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/sidebar.collapse.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-select/assets/lib/js/bootstrap-select.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-select/assets/custom/js/bootstrap-select.init.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/sidebar.kis.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/easy-pie/assets/lib/js/jquery.easy-pie-chart.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/charts/easy-pie/assets/custom/easy-pie.init.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/core.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/animations.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/colorpicker-farbtastic/assets/js/farbtastic.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/select2/assets/lib/js/select2.js?v=v1.9.6&sv=v0.0.1"></script> 

<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-datepicker/assets/lib/js/bootstrap-datepicker.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-datepicker/assets/custom/js/bootstrap-datepicker.init.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.csv-0.71.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.blockUI.js"></script> 
<script src="<?php echo $this->baseUrl(); ?>/assets/components/plugins/holder/holder.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl(); ?>/assets/components/plugins/appear/jquery.appear.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl(); ?>/assets/components/modules/front/core/assets/js/front.core.init.js?v=v1.9.6"></script> 


<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/lib/js/jquery.dataTables.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/custom/js/DT_bootstrap.js?v=v1.9.6&sv=v0.0.1"></script> 
<!--<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/custom/js/datatables.init.js?v=v1.9.6&sv=v0.0.1"></script>--> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/tables/datatables/assets/lib/extras/TableTools/media/js/TableTools.min.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/modules/admin/tables/datatables/assets/lib/extras/ColVis/media/js/ColVis.min.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/jasny-fileupload/assets/js/bootstrap-fileupload.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery-ui.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/common.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/lazyload.js"></script>
<script type="text/javascript">
            
function ConfirmarSalir(){
      window.location = "<?php echo $this->baseUrl() ?>/login/logout";
}
				
	$("img.lazy").lazyload({
    	effect : "fadeIn"
	});
          
        </script>
</body>
</html>