<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<?php
				/* This line outputs the doctype we set in the bootstrap */
				$registry 	= Zend_Registry::getInstance ();
				$auth 		= Zend_Auth::getInstance ();
				$user 		= $auth->getIdentity ();
				$genObj 	= new Default_Model_Generico ();				
				function getSubDomain() {
					$MaxLength = 100; 
					$sub = '';
					$subdomain = addslashes ( htmlentities ( substr ( strtolower ( $_SERVER ['SERVER_NAME'] ), 0, $MaxLength ) ) );
					$subdomain = substr ( $subdomain, 0, strpos ( $subdomain, "." ) );					
					if ($subdomain != 'www' ) {
						$sub = $subdomain;
					}
					return $sub;
				}
				
				$subdomain_var = getSubDomain ();                                
				if (false == empty ( $subdomain_var )) {
					$program = $genObj->getRow ( "subdomain='" . $subdomain_var . "'", "licenses" ); 					                                       
					if (! empty ( $program )) {
						$client = $genObj->getRow ( "id_client=" . $program ['client_id'], "client" );
                        $isRegistrationOpen = $program['registration_page'];
						$logo = $client ['logo'];
						$bg = $client ['bg'];
					} else {
						$logo = 'logo-m8.png';
						$bg = '#FEAF1D';
					}
				}
				
				?>
<title>motive8</title>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/css/custom8/style.css">
<!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body style="background-color:<?php echo $bg; ?>">
<section class="container">
  <div class="login">
    <h1> <img src="<?php echo $this->baseUrl() ?>/uploads/logo/<?php echo $logo; ?>" alt="" style="max-height: 90px; margin-top: 15px"> </h1>
                    
    <form name="formLogin" id="formLogin" action="" method="post" class="form-horizontal row-fluid">

      <input type="hidden" name="client_id" id="client_id" class="row-fluid" value="<?php echo $program['client_id'] != '' ? $program['client_id']:1; ?>">
      <input type="hidden" name="id_licence" id="id_licence" class="row-fluid" value="<?php echo $program['id_licence'] ?>">
      <p><h1><?php echo $program['name'] ?></h1></p>
            <label class="error" for="cname2" generated="true" style="display: block; color:#F00">
        <?php if(!empty($this->message)) echo 'Incorrect username or password.';?>
      </label>
      <p><input type="text" name="username" id="username" placeholder="User Name" class="row-fluid" value=""></p>
      <p><input type="password" name="password" id="password" placeholder="Password" class="row-fluid" value=""></p>            
      <p class="submit"><input type="submit" name="commit" value="Login">
      <?php 
        $subdomain_var = getSubDomain();
        
        if($subdomain_var != ''){        
        $licence_registration = $genObj->getRow_select ( "subdomain='" . $subdomain_var . "'", "licenses", array('registration_page', 'status') );    
		if($licence_registration['registration_page'] == 1 and $licence_registration['status'] == 6){?>
      <a  class="register_button" href='<?php echo $this->baseUrl()."/participant/register/index/licence/{$program['id_licence']}/clientId/{$program['client_id']}"; ?>'>Register</a>
            
        <?php }  } ?>
            </p>
    </form>

  </div>
  <div class="login-help">
  <p> Forgot your password? <a href="<?php echo $this->baseUrl() ?>/login/forget">Click here to reset it</a>. </p> 
    <?php if(!empty($program ['program_admin_email'])){ ?>
    	<p> Program administrator: <?php echo $program ['program_admin_email']; ?>
    <?php }  ?>
   	</p> 
 
 </div> 
</section>
    
</body>
</html>
