<!DOCTYPE html>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 footer-sticky navbar-sticky"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 footer-sticky navbar-sticky"> <![endif]-->
<!--[if gt IE 8]> <html class="ie footer-sticky navbar-sticky"> <![endif]-->
<!--[if !IE]><!-->
<html class="footer-sticky navbar-sticky">
<!-- <![endif]-->
<head>
<title>motive8</title>

<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<?php 
/*This line outputs the doctype we set in the bootstrap */
$registry         = Zend_Registry::getInstance();
$auth             = Zend_Auth::getInstance();
$user             = $auth->getIdentity();
$genObj       	  = new Default_Model_Generico();

$client 	= $genObj->getRow("id_client='".$user['id_client']."'", "client");
$licence 	= $genObj->getRow("id_licence='{$this->id_licence}'", "licenses");


?>
<script type="text/javascript">
	var base_url    = '<?php echo $this->baseUrl() ?>';
	var site_url    = '<?php echo $this->url() ?>';
</script>
<!-- 
	**********************************************************
	In development, use the LESS files and the less.js compiler
	instead of the minified CSS loaded by default.
	**********************************************************
   
<link rel="stylesheet/less" href="<?php echo $this->baseUrl() ?>/assets/less/admin/module.admin.stylesheet-complete.layout_fixed.true.less" /> -->
<!--
[if lt IE 9]><link rel="stylesheet" href="../assets/components/library/bootstrap/css/bootstrap.min.css" /><![endif]-->
<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/assets/css/admin/module.admin.stylesheet-complete.layout_fixed.true.min.css" />
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/jquery/jquery.min.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.validate.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/js/AjaxUpload.2.0.min.js"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/modernizr/modernizr.js?v=v1.9.6&sv=v0.0.1"></script>
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/less-js/less.min.js?v=v1.9.6&sv=v0.0.1"></script>
</head>
<style>
.backgraundImage {
 <?php if($licence['bg_image'] == 'Apple-Prods.png') {
?>  background-image: url(<?php echo $this->baseUrl();
?>/uploads/bg_licences/<?php echo $licence['bg_image'];
?>);
 background-repeat: no-repeat;
 background-attachment: fixed;
 background-position: top;
 <?php
}
else {
?>  background-image: url(<?php echo $this->baseUrl();
?>/uploads/bg_licences/<?php echo $licence['bg_image'];
?>);
	background-repeat: repeat;
	width: 100%;
	height: 100%;
 <?php
}
?>  background-color: <?php echo $licence['color_bg']; ?>;
 -webkit-background-size: cover;
 -moz-background-size: cover;
 -o-background-size: cover;/*background-size:100%;*/
}
/*
.container{
	background-color:#fff;
	max-height:700px;
	min-height:700px;
	}
*/
</style>
<body class=" menu-right-hidden backgraundImage"  >
<!-- Main Container Fluid -->
<div class="container-fluid menu-hidden"> 
  <!-- Content -->
  <div id="content">
    <div class="navbar hidden-print main navbar-default" role="navigation" style="height:100%;">
      <div class="container">
     <?php if (!empty( $licence['banner'])) { ?> 
     <div style="z-index:1000" >
      <img src="<?php echo $this->baseUrl() ?>/uploads/banner/<?php echo $licence['banner']; ?>" alt="" class="img-clean" style="width:100%; max-height:185px"  >			
      </div>
      <?php } else { ?>      
        <div class="navbar-header"><img src="<?php echo $this->baseUrl() ?>/uploads/logo/<?php echo $client['logo']; ?>" alt="" class="img-clean" height="40px" style="margin-top:10px; "></div>
         <?php } ?>
      </div>
    </div>
    

 
     
   
    
    
    <div class="layout-app" >
      <div class="container" >  

        <div class="row row-app margin-none"   style="background-color:#fff;min-height:650px;" > 
            <div id="contenido" ><?php echo $this->layout()->content ?></div>
        </div>
        <!-- // END row-app -->        
      </div>
    </div>
  </div>
 
  <!-- // Content END -->
  <div class="clearfix"></div>
  <!-- // Sidebar menu & content wrapper END --> 
  <!-- Footer -->
  <div id="footer" class="hidden-print"> 
    <!--  Copyright Line -->
    <div class="copy">&copy; <?php echo date('Y') ?> <a href="http://www.motive8.com.au" target="_blank">motive8</a> - All Rights Reserved. <a href="http://ad-inc.com.au" target="_blank">AD+INC</a></div>
    <!--  End Copyright Line --> 
  </div>
  <!-- // Footer END --> 
</div>
<!-- // Main Container Fluid END --> 
<!-- Global --> 
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/assets/js/jquery.populate.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/library/bootstrap/js/bootstrap.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/plugins/breakpoints/breakpoints.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/core.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/core/js/animations.init.js?v=v1.9.6"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-select/assets/lib/js/bootstrap-select.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/select2/assets/lib/js/select2.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/colorpicker-farbtastic/assets/js/farbtastic.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/forms/elements/bootstrap-datepicker/assets/lib/js/bootstrap-datepicker.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/lib/js/jquery.dataTables.min.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/components/common/tables/datatables/assets/custom/js/DT_bootstrap.js?v=v1.9.6&sv=v0.0.1"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery.blockUI.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/common.js"></script> 
<script src="<?php echo $this->baseUrl() ?>/assets/js/jquery-ui.js"></script>



<script type="text/javascript">
    function ConfirmarSalir()
    {
		window.location = "<?php echo $this->baseUrl() ?>/login/logout";
								
     }

</script>
</body>
</html>