
<div class="row">
  <div class="col-md-4">
    <div class="widget widget-heading-simple widget-body-white">
      <div class="widget-body innerAll inner-2x">
        <div class="glyphicons glyphicon-xlarge glyphicon-top display"> <i></i>
          <h4>Welcome to motive8 <?php $name = $user->fullname;
								echo strstr($name, ' ', true); ?>!</h4>
          <p>Please complete the following easy steps to set up and launch your incentive program. </p>
          <p> This will take you about 1hr. However, you can save and come back to complete at any time. </p>
          <p> Need help? Contact us:   
            1300 559 904 </p>
        </div>
      </div>
    </div>
  </div>
 <div class="col-md-4">
    <div class="widget widget-heading-simple widget-body-white">
      <div class="widget-body innerAll inner-2x">      
        <h4>motive8 set up steps</h4>
        <ul class="timeline-activity list-unstyled">
          <li class="active"> <i class="list-icon fa fa-user"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">1 Profile</div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-gift"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">2 Rewards</a><a href=""></a> </div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-group"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">3 Audience</a><a href=""></a> </div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-file-text-o"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">4 Criteria</a><a href=""></a> </div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-flag-checkered"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">5 Target</a><a href=""></a> </div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-shopping-cart"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">6 Points</a><a href=""></a> </div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-bullhorn"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">7 Communicate</a><a href=""></a> </div>
            </div>
          </li>
          <li class="active"> <i class="list-icon fa fa-plane"></i>
            <div class="block block-inline">
            <div class="caret"></div>
            <div class="box-generic">
              <div class="timeline-top-info content-filled border-bottom">8 Launch</a><a href=""></a> </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="widget widget-heading-simple widget-body-white">
      <div class="widget-body innerAll inner-2x">
        <div class="widget-body">
          <div >
            <h4>Before Your Start</h4>
            <p class="margin-none">List of things  you will need</p>
            <p class="margin-none">Audience Template</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
