<!-- col-app -->
<div class="col-app animated fadeInDown">
  <div class="widget">
    <div class="widget-head">
      <h4 class="heading">Welcome <?php echo strstr($this->userDetails->fullname,' ', true); ?>!</h4>
    </div>
    <div class="widget-body innerAll inner-2x"> 
      
      <!-- Table -->
      <table class="table table-striped table-responsive swipe-horizontal table-primary">        
        <!-- Table heading -->
        <thead>
          <tr>
            <th>Licence Name</th>
            <th>Licence Type</th>
            <th>Date from to</th>
            <th>Subdomain</th>
            <th>Status</th>
          </tr>
        </thead>
        <!-- // Table heading END --> 
        
        <!-- Table body -->
        <tbody>
                 <?php
        if (!empty($this->programList)) {
            foreach ($this->programList as $pl) :
                ?> 
          <!-- Table row -->
          <tr>
            <td><?php echo $pl['name'] ?></td>
            <td><?php echo $pl['licenceType'] ?></td>
            <td><?php echo $pl['date_from'] ?> <strong>to</strong> <?php echo $pl['date_from'] ?></td>
            <td><?php echo $pl['subdomain'] ?></td>
            <td><?php echo $pl['statusName'] ?></td>
          </tr> 
        <?php
            endforeach
            ;
        }
        ?>                 
        </tbody>
        <!-- // Table body END -->        
      </table>
      <!-- // Table END -->       
    </div>
  </div>
</div>
<!-- // END col-app --> 

