<script type="text/javascript">
$(document).ready(function() {
	
$('#addProduct').click(function() {
	alert('hol');
});


});
</script>

<form class="form-horizontal" name="frmAdd" id="frmAdd" method="POST" >
  <input type="hidden" id="profile_id" name="fields[program_participants][profile_id]" value="1">
  <div class="row">
    <div class="col-md-6">
      <div class="thumbnail"> <img
					src="<?php echo $this->baseUrl() ?>/uploads/catalog/<?php echo $this->product_info['image']; ?>"
					alt="photo" class="img-responsive" /> </div>
    </div>
    <div class="col-md-6">
      <h1 class="title text-primary"><?php echo $this->product_info['name']; ?></h1>
      <p><?php echo $this->product_info['description']; ?></p>
      <div class="separator"></div>
      <div class="box-generic padding-none">
        <h3 class="strong margin-none innerAll border-bottom text-inverse">Points: <i class="fa  fa-bullseye"></i> <?php echo $this->product_info['points']; ?></h3>
        <div class="innerAll border-bottom">
          <label>QTY:</label>         
          <div class="btn-group innerT">
         	<input type="text" class="form-control required email" id="qty" name="fields[program_participants][email]" placeholder="Qty" value="1" >
          </div>
        </div>
        <div class="innerAll">
          <div class="btn btn-primary strong" id="addProduct"><i class="fa fa-plus"></i>Add to Cart</div>
        </div>
      </div>
    </div>
  </div>
</form>
