<script type="text/javascript">
$(document).ready(function() {
	 

});
</script>
<!-- col -->
<div class="col-md-12">
        <div align="center" style="margin-bottom:50px"><img src="<?php echo $this->baseUrl() ?>/uploads/logo/<?php echo $this->client['logo']; ?>" alt="" class="img-clean" height="75px" style="margin-top:10px; "></div>
<!-- col-table-row -->
<div class="col-table-row">
    <!-- Stats Widgets -->
    <div class="innerAll">
      <div class="row">
	<div class="col-md-4 col-md-offset-1 center">
		<div class="center">
			<img src="<?php echo $this->baseUrl() ?>/assets/images/error-icon-bucket.png " class="error-icon">
		</div>
	</div>
	<div class="col-md-5 content center">
		<h1 class="strong">Oups!</h1>
		<h4 class="innerB">This program is currently on hold. Please como back again soon or contact your program administrator.</h4>
		<div class="well">
	              <p><?php echo $this->licence_info['program_admin_email']; ?></p> 
		</div>
	</div>

  </div>
  <!-- // END col-table-row --> 
</div>
<!-- // END col --> 

