<script type="text/javascript">
$(document).ready(function() {
    
    $("#submit").click(function(){
        if($('#tc').valid()){
            
                        $.post('<?php echo $this->baseUrl() ?>/participant/program/tandc/tabla/program_participants/idname/id_participant/idval/' + $("#id_participant").val(), $("#tc").serialize(), function(data) {
                           
                           console.log(data);
                            if (data == 1) {
                                 //alert("Email address already exit."); 
                                 $( "#tc" ).submit();
                            }                            
                            else {  
//                                console.log(data);
                                 alert("Something goes wrong. Please try later.");
                            }
                        }); //fin function data            
        }
    });


});
</script>


<?php $tc =  $this->tc_accepted; 

 
 if($tc['tc_accepted']== 0){   ?>    
     
<div> 

    <h2>Terms and conditions</h2>
    <p>
        T and C goes here
    </p>
    
<form class="form-horizontal" name="tc" id="tc" action='<?php echo $this->baseUrl()?>/participant/program/index/' method="POST">
<input type="hidden" id="id_participant" name="fields[program_participants][id_participant]"  value="<?php echo $this->id_participant; ?>">     
<div class="form-group">    
    <label class="col-sm-2 control-label">Accepted</label>

    <div class="col-sm-2">
        <input type="checkbox" class="form-control required" id="tc" name="fields[program_participants][tc_accepted]"  placeholder="Terms and Conditions">
    </div>
    <div class="col-sm-offset-2 col-sm-10">
        <div class="btn btn-primary" id="submit">Submit</div>            
    </div>
        
            

</div>
</form>

</div>
     
 <?php    
 } 
?>


<!-- col -->
<div class="col-md-3 col-sm-4" >  
  <!-- col-separator.box -->
  <div class="col-separator box col-separator-first reset-components">
    <div class="bg-white">
      <div class="innerAll">
        <h4><?php echo $this->userinfo['fullname']; ?></h4>
        <p class="margin-none text-muted"><?php echo $this->userinfo['position']; ?></p>
      </div>
    <div class="widget widget-heading-simple widget-body-white"> 
    	<a href="" class="widget-stats widget-stats-gray widget-stats-2"> <span class="count">0</span> <span class="txt">Points</span> </a> 
    </div><br/>
  
    
      <div class="innerLR innerB center">
        <div class="btn-group-vertical display-block margin-none">  
       		<a href="<?php echo $this->baseUrl()?>/participant/participant/edit/" class="btn btn-stroke btn-inverse">My Profile</a> 
        	<a href="#" class="btn btn-stroke btn-inverse"> Wish List</a> 
        	<a href="#" class="btn btn-stroke btn-inverse">Orders</a> </div>
      </div>
    </div>
 <br/>
   </div>

</div>
<!-- // END col --> 

<!-- col -->
<div class="col-md-9 col-sm-8">
<!-- col-table-row -->
<div class="col-table-row">
    <!-- Stats Widgets -->
    <div class="innerAll">
      <div class="row">
       <br/>
          <?php if( $this->page == 1 ) { 
				  	echo $this->licence_detail['welcome_ms'];
				  } else { 
				  	echo $this->licence_detail['criteria']; 
				  } 
		  ?>     
  </div>
  <!-- // END col-table-row --> 
</div>
<!-- // END col --> 

