<script type="text/javascript">
$(document).ready(function() {
	
	 var availableTags =  <?php echo json_encode($this->search_list); ?>;
	
	$( "#search" ).autocomplete({
      	source: availableTags,
	  	select: function (event, ui) { 
			location.href = '<?php echo $this->baseUrl() ?>/participant/program/details/product/'+ui.item.value;
		} 

	}).data("uiAutocomplete")._renderItem = function (ul, item) {
        return $("<li />")
            .data("item.autocomplete", item)
            .append("<a><img style='max-width: 50px; max-height: 50px;'  src='<?php echo $this->baseUrl() ?>/uploads/catalog/" + item.image + "' />" + item.label + "</a>")
            .appendTo(ul);
}; 
 
$('#participant_menu').load('<?php echo $this->baseUrl();?>/participant/program/participant/l/<?php echo $this->id_licence; ?>');
});
</script>

<div class="col-md-3 col-sm-4" >
<!-- col -->
<div class="col-separator box col-separator-first reset-components"  id="participant_menu"><!-- col-separator.box --> 
</div>
<!-- col-separator.box END--> 

<br/>
<div class="col-separator box col-separator-first reset-components">
<h5 class="text-faded">Browse categories</h5>
    <div class="input-group">
      <input type="text" class="form-control" name="search" id="search"	placeholder="Search Product">
      <span class="input-group-btn"> <a	href="#" class="btn btn-default"><i class="fa fa-search"></i></a> </span> 
    </div><br/>

<ul class="list-group list-group-1 margin-none borders-none">
<?php if (! empty ( $this->categories_list )) {				
				foreach ( $this->categories_list as $ctl ) :					
					if (! empty ( $ctl ['qty'] )) { ?>
                        <li class="list-group-item"> 
                        <a href="#menu_tables<?php echo $ctl['id_category']; ?>" data-toggle="collapse"> <span class="badge badge-primary pull-right"><?php echo $ctl['qty'] ?></span> <?php echo $ctl['category'] ?> </a>
                          <?php if (! empty ( $this->subcategories_list )) { ?>
                              <ul class="list-group list-group-1 margin-none borders-none collapse" id="menu_tables<?php echo $ctl['id_category']; ?>">
                                <?php 	foreach ( $this->subcategories_list as $sl ) :
                                    if ( $sl ['id_category'] ==  $ctl ['id_category']) { ?>
                                    	<li class="list-group-item"><a href="<?php echo $this->baseUrl() ?>/participant/program/shop/sct/<?php echo $sl ['id_subcategory']; ?>/ct/<?php echo $ctl['id_category']; ?>/l/<?php echo $this->id_licence; ?>/sctname/<?php echo $sl['subcategory'] ?>"><?php echo $sl['subcategory'] ?><span class="badge badge-primary pull-right"><?php echo $sl['qty'] ?></span></a></li>
                                    <?php	}  ?>
                                <?php	 endforeach;  ?>
                              </ul>
                          <?php	 } ?>
                        </li>
                    <?php	}  ?>
                <?php	 endforeach;  ?>
<?php	 } ?>
</u>

<br/>
</div>
<!-- col-separator.box END--> 
</div>
<!-- // END col --> 



<!-- col -->
<div class="col-md-9 col-sm-8">
<div class="col-table-row">
<!-- Stats Widgets -->
<div class="innerAll">
  <div class="row">
    <h2>Categories</h2>
    <br/>
    <?php if (! empty ( $this->categories_list )) {
				foreach ( $this->categories_list as $sl ) :
					if (! empty ( $sl ['qty'] )) { ?>
    <div class="col-sm-4 col-xs-12">
      <div class="widget widget-pinterest fixed-height" data-animate="bounceIn" data-delay="200">
        <div class="widget-body padding-none"> 
        <a	href="<?php echo $this->baseUrl() ?>/participant/program/shop/ct/<?php echo $sl['id_category']; ?>/l/<?php echo $this->id_licence; ?>" class="thumb"> <img class="img-responsive" src="<?php echo $this->baseUrl() ?>/uploads/category/<?php echo $sl['image']; ?>"></a>
          <div class="description">
            <h5 class="text-uppercase"><?php echo $sl['category'] ?></h5>
            <span class="text-primary text-medium text-condensed"><?php echo $sl['qty'] ?></span> 
          </div>
        </div>
      </div>
    </div>
    <?php	} endforeach; } ?>
  </div>
  <!-- // END row --> 
</div>
<!-- // END Widgets --> 
 

