<script type="text/javascript">
$(document).ready(function() {
	
	$("img.lazy").lazyload({
    	effect : "fadeIn"
	});

	 var availableTags =  <?php echo json_encode($this->search_list); ?>;
	
	$( "#search" ).autocomplete({
      	source: availableTags,
	  	select: function (event, ui) { 
			location.href = '<?php echo $this->baseUrl() ?>/participant/program/details/product/'+ui.item.value;
		} 

	}).data("uiAutocomplete")._renderItem = function (ul, item) {
        return $("<li />")
            .data("item.autocomplete", item)
            .append("<a><img style='max-width: 50px; max-height: 50px;'  src='<?php echo $this->baseUrl() ?>/uploads/catalog/" + item.image + "' />" + item.label + "</a>")
            .appendTo(ul);
}; 

$('#participant_menu').load('<?php echo $this->baseUrl();?>/participant/program/participant/l/<?php echo $this->licence_detail['id_licence']; ?>');
	
$('.prodcss').click(function() {
	$('#product-detail').load('<?php echo $this->baseUrl();?>/participant/program/details/product/'+$(this).attr('rel'));
});


});
</script>

<!-- col -->
<div class="col-md-3 col-sm-4" >  
  <!-- col-separator.box -->
  <div class="col-separator box col-separator-first reset-components" id="participant_menu">
  </div>  
 <br/>
 <div class="col-separator box col-separator-first reset-components">
 <h5 class="text-faded">Browse categories</h5>
        <div class="input-group">
			<input type="text" class="form-control" name="search" id="search"
				placeholder="Search Product"> <span class="input-group-btn"> <a
				href="#" class="btn btn-default"><i class="fa fa-search"></i></a>
			</span>
		</div><br/>
 <ul class="list-group list-group-1 margin-none borders-none">   
    <?php  if (! empty ( $this->categories_list )) {				
				foreach ( $this->categories_list as $ctl ) :					
					if (! empty ( $ctl ['qty'] )) { ?>
                    <li class="list-group-item <?php echo $this->categoryId == $ctl['id_category'] ? 'active':''; ?>">
                        <a href="#menu_tables<?php echo $ctl['id_category']; ?>" data-toggle="collapse">
                            <span class="badge badge-primary pull-right"><?php echo $ctl['qty'] ?></span>
                            <?php echo $ctl['category'] ?>
                        </a>                        
                         <?php if (! empty ( $this->subcategories_list )) { ?>
							 <ul class="list-group list-group-1 margin-none borders-none <?php echo $this->categoryId == $ctl['id_category'] ? 'in':'collapse'; ?>" id="menu_tables<?php echo $ctl['id_category']; ?>">							   
							   <?php 	foreach ( $this->subcategories_list as $sl ) :
									if ( $sl ['id_category'] ==  $ctl ['id_category']) { ?>                                     
                                       <li class="list-group-item"><a href="<?php echo $this->baseUrl() ?>/participant/program/shop/sct/<?php echo $sl ['id_subcategory']; ?>/ct/<?php echo $ctl['id_category']; ?>/sctname/<?php echo $sl['subcategory'] ?>"><span class="badge badge-primary pull-right"><?php echo $sl['qty'] ?></span><?php echo $sl['subcategory'] ?></a></li>
								<?php	}  ?>                
                            <?php	 endforeach;  ?> 
                             </ul>
                      <?php	 } ?> 
                     </li>
        		<?php	}  ?>                
      		<?php	 endforeach;  ?> 
      <?php	 } ?> 	
</u>

  </div>
<br/>

          
</div>
<!-- // END col -->   
    
<!-- col -->
<div class="col-md-9 col-sm-8">
<!-- col-table-row -->
<div class="col-table-row">
    <!-- Stats Widgets -->
    <div class="innerAll">
      <div class="row">
		<h2 class=" margin-none"><?php echo $this->category_info['category']; ?><?php echo $this->sc_name; ?></h2>
		<br />
  
		<?php	if (! empty ( $this->products_list )) {
				foreach ( $this->products_list as $sl ) : ?>
            <div class="col-sm-4 col-xs-12">
				<div class="widget widget-pinterest fixed-height"
					data-animate="bounceIn" data-delay="200">
					<div class="widget-body padding-none">
						 <a data-toggle="modal" data-target="#ProductDetail" class="thumb prodcss" href="#" rel="<?php echo $sl['id'] ?>"> 
                            <img class="lazy img-responsive" data-original="<?php echo $this->baseUrl() ?>/uploads/catalog/<?php echo htmlspecialchars($sl['image']); ?>">
                        </a>
						<div class="description">
                        <a data-toggle="modal" data-target="#ProductDetail" class="btn btn-primary btn-circle pull-right prodcss" href="#" rel="<?php echo $sl['id'] ?>"> 
						<i
								class="fa fa-shopping-cart"></i></a> <span
								class="text-primary text-medium text-condensed"><i class="fa  fa-bullseye"></i> <?php echo $sl['points'] ?></span>
							<h5 class="text-uppercase expander" style="min-height: 80px;"><?php echo $sl['name'] ?></h5>
						</div>
					</div>
				</div>
			</div>
            <?php endforeach; } ?>
  </div>
  <!-- // END col-table-row --> 
</div>
<!-- // END col --> 
